stages:
  - test

variables:
  GOPATH: ${CI_PROJECT_DIR}/.go
  GOFLAGS: -mod=readonly

default:
  image: golang:1.26.9-alpine3.23@sha256:96123126ac58e910f4dd3619a8901e2fb6d1ad84b59b1232cac7c9ea65a8f888
  cache:
    key: go-mod-${CI_COMMIT_REF_SLUG}
    paths:
      - .go/pkg/mod/

test:
  stage: test
  before_script:
    - go mod download
  script:
    - go build ./...
    - go vet ./...
    - go test -race -coverprofile=coverage.out ./...
    - go tool cover -func=coverage.out | tail -1
  coverage: '/total:\s+\(statements\)\s+(\d+\.\d+)%/'
