//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for ExecutionStatus.
const (
	ExecutionStatusDelivered  ExecutionStatus = "delivered"
	ExecutionStatusEmitted    ExecutionStatus = "emitted"
	ExecutionStatusFailed     ExecutionStatus = "failed"
	ExecutionStatusInProgress ExecutionStatus = "in_progress"
)

// Valid indicates whether the value is a known member of the ExecutionStatus enum.
func (e ExecutionStatus) Valid() bool {
	switch e {
	case ExecutionStatusDelivered:
		return true
	case ExecutionStatusEmitted:
		return true
	case ExecutionStatusFailed:
		return true
	case ExecutionStatusInProgress:
		return true
	default:
		return false
	}
}

// Defines values for ExecutionTriggerType.
const (
	ExecutionTriggerTypeManual    ExecutionTriggerType = "manual"
	ExecutionTriggerTypeScheduled ExecutionTriggerType = "scheduled"
)

// Valid indicates whether the value is a known member of the ExecutionTriggerType enum.
func (e ExecutionTriggerType) Valid() bool {
	switch e {
	case ExecutionTriggerTypeManual:
		return true
	case ExecutionTriggerTypeScheduled:
		return true
	default:
		return false
	}
}

// Defines values for ListExecutionsParamsStatus.
const (
	ListExecutionsParamsStatusDelivered  ListExecutionsParamsStatus = "delivered"
	ListExecutionsParamsStatusEmitted    ListExecutionsParamsStatus = "emitted"
	ListExecutionsParamsStatusFailed     ListExecutionsParamsStatus = "failed"
	ListExecutionsParamsStatusInProgress ListExecutionsParamsStatus = "in_progress"
)

// Valid indicates whether the value is a known member of the ListExecutionsParamsStatus enum.
func (e ListExecutionsParamsStatus) Valid() bool {
	switch e {
	case ListExecutionsParamsStatusDelivered:
		return true
	case ListExecutionsParamsStatusEmitted:
		return true
	case ListExecutionsParamsStatusFailed:
		return true
	case ListExecutionsParamsStatusInProgress:
		return true
	default:
		return false
	}
}

// Defines values for ListExecutionsParamsTriggerType.
const (
	ListExecutionsParamsTriggerTypeManual    ListExecutionsParamsTriggerType = "manual"
	ListExecutionsParamsTriggerTypeScheduled ListExecutionsParamsTriggerType = "scheduled"
)

// Valid indicates whether the value is a known member of the ListExecutionsParamsTriggerType enum.
func (e ListExecutionsParamsTriggerType) Valid() bool {
	switch e {
	case ListExecutionsParamsTriggerTypeManual:
		return true
	case ListExecutionsParamsTriggerTypeScheduled:
		return true
	default:
		return false
	}
}

// APIKeyInfo defines model for APIKeyInfo.
type APIKeyInfo struct {
	CreatedAt  time.Time          `json:"created_at"`
	Enabled    bool               `json:"enabled"`
	Id         openapi_types.UUID `json:"id"`
	Label      string             `json:"label"`
	LastUsedAt *time.Time         `json:"last_used_at,omitempty"`
	Namespace  string             `json:"namespace"`
}

// CreateAPIKeyRequest defines model for CreateAPIKeyRequest.
type CreateAPIKeyRequest struct {
	Label     string `json:"label"`
	Namespace string `json:"namespace"`
}

// CreateAPIKeyResponse defines model for CreateAPIKeyResponse.
type CreateAPIKeyResponse struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Label     string             `json:"label"`
	Namespace string             `json:"namespace"`

	// Token Plaintext token. Only returned on creation.
	Token string `json:"token"`
}

// CreateJobRequest defines model for CreateJobRequest.
type CreateJobRequest struct {
	Analytics *struct {
		RetentionSeconds *int `json:"retention_seconds,omitempty"`
	} `json:"analytics,omitempty"`
	CronExpression string `json:"cron_expression"`
	Name           string `json:"name"`

	// Tags Key-value tag pairs
	Tags                  *Tag    `json:"tags,omitempty"`
	Timezone              string  `json:"timezone"`
	WebhookSecret         *string `json:"webhook_secret,omitempty"`
	WebhookTimeoutSeconds *int    `json:"webhook_timeout_seconds,omitempty"`
	WebhookUrl            string  `json:"webhook_url"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    string                  `json:"code"`
		Details *map[string]interface{} `json:"details,omitempty"`
		Message string                  `json:"message"`
	} `json:"error"`
}

// Execution defines model for Execution.
type Execution struct {
	AcknowledgedAt *time.Time           `json:"acknowledged_at,omitempty"`
	CreatedAt      time.Time            `json:"created_at"`
	FiredAt        time.Time            `json:"fired_at"`
	Id             openapi_types.UUID   `json:"id"`
	JobId          openapi_types.UUID   `json:"job_id"`
	ScheduledAt    time.Time            `json:"scheduled_at"`
	Status         ExecutionStatus      `json:"status"`
	TriggerType    ExecutionTriggerType `json:"trigger_type"`
}

// ExecutionStatus defines model for Execution.Status.
type ExecutionStatus string

// ExecutionTriggerType defines model for Execution.TriggerType.
type ExecutionTriggerType string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Database *string `json:"database,omitempty"`
	Status   string  `json:"status"`
}

// Job defines model for Job.
type Job struct {
	CreatedAt      time.Time          `json:"created_at"`
	CronExpression string             `json:"cron_expression"`
	Enabled        bool               `json:"enabled"`
	Id             openapi_types.UUID `json:"id"`
	Name           string             `json:"name"`
	Namespace      string             `json:"namespace"`

	// Tags Key-value tag pairs
	Tags       *Tag      `json:"tags,omitempty"`
	Timezone   string    `json:"timezone"`
	UpdatedAt  time.Time `json:"updated_at"`
	WebhookUrl string    `json:"webhook_url"`
}

// JobDetail defines model for JobDetail.
type JobDetail struct {
	CreatedAt        time.Time          `json:"created_at"`
	CronExpression   string             `json:"cron_expression"`
	Enabled          bool               `json:"enabled"`
	Id               openapi_types.UUID `json:"id"`
	Name             string             `json:"name"`
	Namespace        string             `json:"namespace"`
	RecentExecutions *[]Execution       `json:"recent_executions,omitempty"`

	// Tags Key-value tag pairs
	Tags       *Tag      `json:"tags,omitempty"`
	Timezone   string    `json:"timezone"`
	UpdatedAt  time.Time `json:"updated_at"`
	WebhookUrl string    `json:"webhook_url"`
}

// NextRunResponse defines model for NextRunResponse.
type NextRunResponse struct {
	CronExpression string      `json:"cron_expression"`
	NextRunAt      time.Time   `json:"next_run_at"`
	NextRuns       []time.Time `json:"next_runs"`
	Timezone       string      `json:"timezone"`
}

// ResolveScheduleRequest defines model for ResolveScheduleRequest.
type ResolveScheduleRequest struct {
	// Description Natural language schedule or cron expression
	Description string  `json:"description"`
	Timezone    *string `json:"timezone,omitempty"`
}

// ResolveScheduleResponse defines model for ResolveScheduleResponse.
type ResolveScheduleResponse struct {
	CronExpression string      `json:"cron_expression"`
	Description    string      `json:"description"`
	NextRuns       []time.Time `json:"next_runs"`
	Timezone       string      `json:"timezone"`
}

// Tag Key-value tag pairs
type Tag map[string]string

// UpdateJobRequest defines model for UpdateJobRequest.
type UpdateJobRequest struct {
	CronExpression *string `json:"cron_expression,omitempty"`
	Enabled        *bool   `json:"enabled,omitempty"`
	Name           *string `json:"name,omitempty"`

	// Tags Key-value tag pairs
	Tags                  *Tag    `json:"tags,omitempty"`
	Timezone              *string `json:"timezone,omitempty"`
	WebhookSecret         *string `json:"webhook_secret,omitempty"`
	WebhookTimeoutSeconds *int    `json:"webhook_timeout_seconds,omitempty"`
	WebhookUrl            *string `json:"webhook_url,omitempty"`
}

// APIKeyId defines model for APIKeyId.
type APIKeyId = openapi_types.UUID

// ExecutionId defines model for ExecutionId.
type ExecutionId = openapi_types.UUID

// JobId defines model for JobId.
type JobId = openapi_types.UUID

// LimitParam defines model for LimitParam.
type LimitParam = int

// OffsetParam defines model for OffsetParam.
type OffsetParam = int

// ListAPIKeysParams defines parameters for ListAPIKeys.
type ListAPIKeysParams struct {
	Limit  *LimitParam  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *OffsetParam `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetHealthParams defines parameters for GetHealth.
type GetHealthParams struct {
	Verbose *bool `form:"verbose,omitempty" json:"verbose,omitempty"`
}

// ListJobsParams defines parameters for ListJobs.
type ListJobsParams struct {
	Limit  *LimitParam  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *OffsetParam `form:"offset,omitempty" json:"offset,omitempty"`

	// Tag Filter by tag (key:value format, repeatable, AND semantics)
	Tag     *[]string `form:"tag,omitempty" json:"tag,omitempty"`
	Enabled *bool     `form:"enabled,omitempty" json:"enabled,omitempty"`

	// Name Substring match on job name
	Name *string `form:"name,omitempty" json:"name,omitempty"`
}

// ListExecutionsParams defines parameters for ListExecutions.
type ListExecutionsParams struct {
	Limit       *LimitParam                      `form:"limit,omitempty" json:"limit,omitempty"`
	Offset      *OffsetParam                     `form:"offset,omitempty" json:"offset,omitempty"`
	Status      *ListExecutionsParamsStatus      `form:"status,omitempty" json:"status,omitempty"`
	TriggerType *ListExecutionsParamsTriggerType `form:"trigger_type,omitempty" json:"trigger_type,omitempty"`
	Since       *time.Time                       `form:"since,omitempty" json:"since,omitempty"`
	Until       *time.Time                       `form:"until,omitempty" json:"until,omitempty"`
}

// ListExecutionsParamsStatus defines parameters for ListExecutions.
type ListExecutionsParamsStatus string

// ListExecutionsParamsTriggerType defines parameters for ListExecutions.
type ListExecutionsParamsTriggerType string

// CreateAPIKeyJSONRequestBody defines body for CreateAPIKey for application/json ContentType.
type CreateAPIKeyJSONRequestBody = CreateAPIKeyRequest

// CreateJobJSONRequestBody defines body for CreateJob for application/json ContentType.
type CreateJobJSONRequestBody = CreateJobRequest

// UpdateJobJSONRequestBody defines body for UpdateJob for application/json ContentType.
type UpdateJobJSONRequestBody = UpdateJobRequest

// ResolveScheduleJSONRequestBody defines body for ResolveSchedule for application/json ContentType.
type ResolveScheduleJSONRequestBody = ResolveScheduleRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List API keys in caller's namespace
	// (GET /api-keys)
	ListAPIKeys(w http.ResponseWriter, r *http.Request, params ListAPIKeysParams)
	// Create a new API key
	// (POST /api-keys)
	CreateAPIKey(w http.ResponseWriter, r *http.Request)
	// Revoke an API key
	// (DELETE /api-keys/{id})
	DeleteAPIKey(w http.ResponseWriter, r *http.Request, id APIKeyId)
	// Get execution detail with delivery attempts
	// (GET /executions/{id})
	GetExecution(w http.ResponseWriter, r *http.Request, id ExecutionId)
	// Health check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request, params GetHealthParams)
	// List jobs in caller's namespace
	// (GET /jobs)
	ListJobs(w http.ResponseWriter, r *http.Request, params ListJobsParams)
	// Create a new cron job
	// (POST /jobs)
	CreateJob(w http.ResponseWriter, r *http.Request)
	// Delete a job and its data
	// (DELETE /jobs/{id})
	DeleteJob(w http.ResponseWriter, r *http.Request, id JobId)
	// Get job detail with recent executions
	// (GET /jobs/{id})
	GetJob(w http.ResponseWriter, r *http.Request, id JobId)
	// Partial update a job
	// (PATCH /jobs/{id})
	UpdateJob(w http.ResponseWriter, r *http.Request, id JobId)
	// List executions for a job
	// (GET /jobs/{id}/executions)
	ListExecutions(w http.ResponseWriter, r *http.Request, id JobId, params ListExecutionsParams)
	// Get next scheduled run time
	// (GET /jobs/{id}/next-run)
	GetNextRun(w http.ResponseWriter, r *http.Request, id JobId)
	// Pause a job (set enabled=false)
	// (POST /jobs/{id}/pause)
	PauseJob(w http.ResponseWriter, r *http.Request, id JobId)
	// Resume a paused job (set enabled=true)
	// (POST /jobs/{id}/resume)
	ResumeJob(w http.ResponseWriter, r *http.Request, id JobId)
	// Trigger immediate execution
	// (POST /jobs/{id}/trigger)
	TriggerJob(w http.ResponseWriter, r *http.Request, id JobId)
	// Resolve natural language to cron expression
	// (POST /schedules/resolve)
	ResolveSchedule(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAPIKeys operation middleware
func (siw *ServerInterfaceWrapper) ListAPIKeys(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAPIKeysParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAPIKeys(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAPIKey operation middleware
func (siw *ServerInterfaceWrapper) CreateAPIKey(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAPIKey(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAPIKey operation middleware
func (siw *ServerInterfaceWrapper) DeleteAPIKey(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id APIKeyId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAPIKey(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetExecution operation middleware
func (siw *ServerInterfaceWrapper) GetExecution(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ExecutionId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetExecution(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetHealthParams

	// ------------- Optional query parameter "verbose" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "verbose", r.URL.Query(), &params.Verbose, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "verbose", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListJobs operation middleware
func (siw *ServerInterfaceWrapper) ListJobs(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListJobsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tag", r.URL.Query(), &params.Tag, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		return
	}

	// ------------- Optional query parameter "enabled" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "enabled", r.URL.Query(), &params.Enabled, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "enabled", Err: err})
		return
	}

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "name", r.URL.Query(), &params.Name, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListJobs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateJob operation middleware
func (siw *ServerInterfaceWrapper) CreateJob(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateJob(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteJob operation middleware
func (siw *ServerInterfaceWrapper) DeleteJob(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetJob operation middleware
func (siw *ServerInterfaceWrapper) GetJob(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateJob operation middleware
func (siw *ServerInterfaceWrapper) UpdateJob(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListExecutions operation middleware
func (siw *ServerInterfaceWrapper) ListExecutions(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListExecutionsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "trigger_type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "trigger_type", r.URL.Query(), &params.TriggerType, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "trigger_type", Err: err})
		return
	}

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "since", r.URL.Query(), &params.Since, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		return
	}

	// ------------- Optional query parameter "until" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "until", r.URL.Query(), &params.Until, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "until", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListExecutions(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNextRun operation middleware
func (siw *ServerInterfaceWrapper) GetNextRun(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNextRun(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PauseJob operation middleware
func (siw *ServerInterfaceWrapper) PauseJob(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PauseJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResumeJob operation middleware
func (siw *ServerInterfaceWrapper) ResumeJob(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResumeJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerJob operation middleware
func (siw *ServerInterfaceWrapper) TriggerJob(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResolveSchedule operation middleware
func (siw *ServerInterfaceWrapper) ResolveSchedule(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResolveSchedule(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api-keys", wrapper.ListAPIKeys)
	m.HandleFunc("POST "+options.BaseURL+"/api-keys", wrapper.CreateAPIKey)
	m.HandleFunc("DELETE "+options.BaseURL+"/api-keys/{id}", wrapper.DeleteAPIKey)
	m.HandleFunc("GET "+options.BaseURL+"/executions/{id}", wrapper.GetExecution)
	m.HandleFunc("GET "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc("GET "+options.BaseURL+"/jobs", wrapper.ListJobs)
	m.HandleFunc("POST "+options.BaseURL+"/jobs", wrapper.CreateJob)
	m.HandleFunc("DELETE "+options.BaseURL+"/jobs/{id}", wrapper.DeleteJob)
	m.HandleFunc("GET "+options.BaseURL+"/jobs/{id}", wrapper.GetJob)
	m.HandleFunc("PATCH "+options.BaseURL+"/jobs/{id}", wrapper.UpdateJob)
	m.HandleFunc("GET "+options.BaseURL+"/jobs/{id}/executions", wrapper.ListExecutions)
	m.HandleFunc("GET "+options.BaseURL+"/jobs/{id}/next-run", wrapper.GetNextRun)
	m.HandleFunc("POST "+options.BaseURL+"/jobs/{id}/pause", wrapper.PauseJob)
	m.HandleFunc("POST "+options.BaseURL+"/jobs/{id}/resume", wrapper.ResumeJob)
	m.HandleFunc("POST "+options.BaseURL+"/jobs/{id}/trigger", wrapper.TriggerJob)
	m.HandleFunc("POST "+options.BaseURL+"/schedules/resolve", wrapper.ResolveSchedule)

	return m
}

type ListAPIKeysRequestObject struct {
	Params ListAPIKeysParams
}

type ListAPIKeysResponseObject interface {
	VisitListAPIKeysResponse(w http.ResponseWriter) error
}

type ListAPIKeys200JSONResponse struct {
	Keys []APIKeyInfo `json:"keys"`
}

func (response ListAPIKeys200JSONResponse) VisitListAPIKeysResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateAPIKeyRequestObject struct {
	Body *CreateAPIKeyJSONRequestBody
}

type CreateAPIKeyResponseObject interface {
	VisitCreateAPIKeyResponse(w http.ResponseWriter) error
}

type CreateAPIKey201JSONResponse CreateAPIKeyResponse

func (response CreateAPIKey201JSONResponse) VisitCreateAPIKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAPIKeyRequestObject struct {
	Id APIKeyId `json:"id"`
}

type DeleteAPIKeyResponseObject interface {
	VisitDeleteAPIKeyResponse(w http.ResponseWriter) error
}

type DeleteAPIKey204Response struct {
}

func (response DeleteAPIKey204Response) VisitDeleteAPIKeyResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteAPIKey404JSONResponse Error

func (response DeleteAPIKey404JSONResponse) VisitDeleteAPIKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetExecutionRequestObject struct {
	Id ExecutionId `json:"id"`
}

type GetExecutionResponseObject interface {
	VisitGetExecutionResponse(w http.ResponseWriter) error
}

type GetExecution200JSONResponse Execution

func (response GetExecution200JSONResponse) VisitGetExecutionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetExecution404JSONResponse Error

func (response GetExecution404JSONResponse) VisitGetExecutionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthRequestObject struct {
	Params GetHealthParams
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListJobsRequestObject struct {
	Params ListJobsParams
}

type ListJobsResponseObject interface {
	VisitListJobsResponse(w http.ResponseWriter) error
}

type ListJobs200JSONResponse struct {
	Jobs []Job `json:"jobs"`
}

func (response ListJobs200JSONResponse) VisitListJobsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateJobRequestObject struct {
	Body *CreateJobJSONRequestBody
}

type CreateJobResponseObject interface {
	VisitCreateJobResponse(w http.ResponseWriter) error
}

type CreateJob201JSONResponse JobDetail

func (response CreateJob201JSONResponse) VisitCreateJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateJob422JSONResponse Error

func (response CreateJob422JSONResponse) VisitCreateJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type DeleteJobRequestObject struct {
	Id JobId `json:"id"`
}

type DeleteJobResponseObject interface {
	VisitDeleteJobResponse(w http.ResponseWriter) error
}

type DeleteJob204Response struct {
}

func (response DeleteJob204Response) VisitDeleteJobResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteJob404JSONResponse Error

func (response DeleteJob404JSONResponse) VisitDeleteJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetJobRequestObject struct {
	Id JobId `json:"id"`
}

type GetJobResponseObject interface {
	VisitGetJobResponse(w http.ResponseWriter) error
}

type GetJob200JSONResponse JobDetail

func (response GetJob200JSONResponse) VisitGetJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetJob404JSONResponse Error

func (response GetJob404JSONResponse) VisitGetJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateJobRequestObject struct {
	Id   JobId `json:"id"`
	Body *UpdateJobJSONRequestBody
}

type UpdateJobResponseObject interface {
	VisitUpdateJobResponse(w http.ResponseWriter) error
}

type UpdateJob200JSONResponse JobDetail

func (response UpdateJob200JSONResponse) VisitUpdateJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateJob404JSONResponse Error

func (response UpdateJob404JSONResponse) VisitUpdateJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateJob422JSONResponse Error

func (response UpdateJob422JSONResponse) VisitUpdateJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type ListExecutionsRequestObject struct {
	Id     JobId `json:"id"`
	Params ListExecutionsParams
}

type ListExecutionsResponseObject interface {
	VisitListExecutionsResponse(w http.ResponseWriter) error
}

type ListExecutions200JSONResponse struct {
	Executions []Execution `json:"executions"`
}

func (response ListExecutions200JSONResponse) VisitListExecutionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetNextRunRequestObject struct {
	Id JobId `json:"id"`
}

type GetNextRunResponseObject interface {
	VisitGetNextRunResponse(w http.ResponseWriter) error
}

type GetNextRun200JSONResponse NextRunResponse

func (response GetNextRun200JSONResponse) VisitGetNextRunResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetNextRun404JSONResponse Error

func (response GetNextRun404JSONResponse) VisitGetNextRunResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PauseJobRequestObject struct {
	Id JobId `json:"id"`
}

type PauseJobResponseObject interface {
	VisitPauseJobResponse(w http.ResponseWriter) error
}

type PauseJob200JSONResponse Job

func (response PauseJob200JSONResponse) VisitPauseJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PauseJob404JSONResponse Error

func (response PauseJob404JSONResponse) VisitPauseJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ResumeJobRequestObject struct {
	Id JobId `json:"id"`
}

type ResumeJobResponseObject interface {
	VisitResumeJobResponse(w http.ResponseWriter) error
}

type ResumeJob200JSONResponse Job

func (response ResumeJob200JSONResponse) VisitResumeJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ResumeJob404JSONResponse Error

func (response ResumeJob404JSONResponse) VisitResumeJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type TriggerJobRequestObject struct {
	Id JobId `json:"id"`
}

type TriggerJobResponseObject interface {
	VisitTriggerJobResponse(w http.ResponseWriter) error
}

type TriggerJob201JSONResponse Execution

func (response TriggerJob201JSONResponse) VisitTriggerJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type TriggerJob404JSONResponse Error

func (response TriggerJob404JSONResponse) VisitTriggerJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type TriggerJob409JSONResponse Error

func (response TriggerJob409JSONResponse) VisitTriggerJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type ResolveScheduleRequestObject struct {
	Body *ResolveScheduleJSONRequestBody
}

type ResolveScheduleResponseObject interface {
	VisitResolveScheduleResponse(w http.ResponseWriter) error
}

type ResolveSchedule200JSONResponse ResolveScheduleResponse

func (response ResolveSchedule200JSONResponse) VisitResolveScheduleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ResolveSchedule422JSONResponse Error

func (response ResolveSchedule422JSONResponse) VisitResolveScheduleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List API keys in caller's namespace
	// (GET /api-keys)
	ListAPIKeys(ctx context.Context, request ListAPIKeysRequestObject) (ListAPIKeysResponseObject, error)
	// Create a new API key
	// (POST /api-keys)
	CreateAPIKey(ctx context.Context, request CreateAPIKeyRequestObject) (CreateAPIKeyResponseObject, error)
	// Revoke an API key
	// (DELETE /api-keys/{id})
	DeleteAPIKey(ctx context.Context, request DeleteAPIKeyRequestObject) (DeleteAPIKeyResponseObject, error)
	// Get execution detail with delivery attempts
	// (GET /executions/{id})
	GetExecution(ctx context.Context, request GetExecutionRequestObject) (GetExecutionResponseObject, error)
	// Health check
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// List jobs in caller's namespace
	// (GET /jobs)
	ListJobs(ctx context.Context, request ListJobsRequestObject) (ListJobsResponseObject, error)
	// Create a new cron job
	// (POST /jobs)
	CreateJob(ctx context.Context, request CreateJobRequestObject) (CreateJobResponseObject, error)
	// Delete a job and its data
	// (DELETE /jobs/{id})
	DeleteJob(ctx context.Context, request DeleteJobRequestObject) (DeleteJobResponseObject, error)
	// Get job detail with recent executions
	// (GET /jobs/{id})
	GetJob(ctx context.Context, request GetJobRequestObject) (GetJobResponseObject, error)
	// Partial update a job
	// (PATCH /jobs/{id})
	UpdateJob(ctx context.Context, request UpdateJobRequestObject) (UpdateJobResponseObject, error)
	// List executions for a job
	// (GET /jobs/{id}/executions)
	ListExecutions(ctx context.Context, request ListExecutionsRequestObject) (ListExecutionsResponseObject, error)
	// Get next scheduled run time
	// (GET /jobs/{id}/next-run)
	GetNextRun(ctx context.Context, request GetNextRunRequestObject) (GetNextRunResponseObject, error)
	// Pause a job (set enabled=false)
	// (POST /jobs/{id}/pause)
	PauseJob(ctx context.Context, request PauseJobRequestObject) (PauseJobResponseObject, error)
	// Resume a paused job (set enabled=true)
	// (POST /jobs/{id}/resume)
	ResumeJob(ctx context.Context, request ResumeJobRequestObject) (ResumeJobResponseObject, error)
	// Trigger immediate execution
	// (POST /jobs/{id}/trigger)
	TriggerJob(ctx context.Context, request TriggerJobRequestObject) (TriggerJobResponseObject, error)
	// Resolve natural language to cron expression
	// (POST /schedules/resolve)
	ResolveSchedule(ctx context.Context, request ResolveScheduleRequestObject) (ResolveScheduleResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListAPIKeys operation middleware
func (sh *strictHandler) ListAPIKeys(w http.ResponseWriter, r *http.Request, params ListAPIKeysParams) {
	var request ListAPIKeysRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAPIKeys(ctx, request.(ListAPIKeysRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAPIKeys")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAPIKeysResponseObject); ok {
		if err := validResponse.VisitListAPIKeysResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateAPIKey operation middleware
func (sh *strictHandler) CreateAPIKey(w http.ResponseWriter, r *http.Request) {
	var request CreateAPIKeyRequestObject

	var body CreateAPIKeyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAPIKey(ctx, request.(CreateAPIKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAPIKey")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateAPIKeyResponseObject); ok {
		if err := validResponse.VisitCreateAPIKeyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteAPIKey operation middleware
func (sh *strictHandler) DeleteAPIKey(w http.ResponseWriter, r *http.Request, id APIKeyId) {
	var request DeleteAPIKeyRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteAPIKey(ctx, request.(DeleteAPIKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteAPIKey")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteAPIKeyResponseObject); ok {
		if err := validResponse.VisitDeleteAPIKeyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetExecution operation middleware
func (sh *strictHandler) GetExecution(w http.ResponseWriter, r *http.Request, id ExecutionId) {
	var request GetExecutionRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetExecution(ctx, request.(GetExecutionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetExecution")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetExecutionResponseObject); ok {
		if err := validResponse.VisitGetExecutionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request, params GetHealthParams) {
	var request GetHealthRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListJobs operation middleware
func (sh *strictHandler) ListJobs(w http.ResponseWriter, r *http.Request, params ListJobsParams) {
	var request ListJobsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListJobs(ctx, request.(ListJobsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListJobs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListJobsResponseObject); ok {
		if err := validResponse.VisitListJobsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateJob operation middleware
func (sh *strictHandler) CreateJob(w http.ResponseWriter, r *http.Request) {
	var request CreateJobRequestObject

	var body CreateJobJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateJob(ctx, request.(CreateJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateJobResponseObject); ok {
		if err := validResponse.VisitCreateJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteJob operation middleware
func (sh *strictHandler) DeleteJob(w http.ResponseWriter, r *http.Request, id JobId) {
	var request DeleteJobRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteJob(ctx, request.(DeleteJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteJobResponseObject); ok {
		if err := validResponse.VisitDeleteJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetJob operation middleware
func (sh *strictHandler) GetJob(w http.ResponseWriter, r *http.Request, id JobId) {
	var request GetJobRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetJob(ctx, request.(GetJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetJobResponseObject); ok {
		if err := validResponse.VisitGetJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateJob operation middleware
func (sh *strictHandler) UpdateJob(w http.ResponseWriter, r *http.Request, id JobId) {
	var request UpdateJobRequestObject

	request.Id = id

	var body UpdateJobJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateJob(ctx, request.(UpdateJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateJobResponseObject); ok {
		if err := validResponse.VisitUpdateJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListExecutions operation middleware
func (sh *strictHandler) ListExecutions(w http.ResponseWriter, r *http.Request, id JobId, params ListExecutionsParams) {
	var request ListExecutionsRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListExecutions(ctx, request.(ListExecutionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListExecutions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListExecutionsResponseObject); ok {
		if err := validResponse.VisitListExecutionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetNextRun operation middleware
func (sh *strictHandler) GetNextRun(w http.ResponseWriter, r *http.Request, id JobId) {
	var request GetNextRunRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetNextRun(ctx, request.(GetNextRunRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetNextRun")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetNextRunResponseObject); ok {
		if err := validResponse.VisitGetNextRunResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PauseJob operation middleware
func (sh *strictHandler) PauseJob(w http.ResponseWriter, r *http.Request, id JobId) {
	var request PauseJobRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PauseJob(ctx, request.(PauseJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PauseJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PauseJobResponseObject); ok {
		if err := validResponse.VisitPauseJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ResumeJob operation middleware
func (sh *strictHandler) ResumeJob(w http.ResponseWriter, r *http.Request, id JobId) {
	var request ResumeJobRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ResumeJob(ctx, request.(ResumeJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ResumeJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ResumeJobResponseObject); ok {
		if err := validResponse.VisitResumeJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TriggerJob operation middleware
func (sh *strictHandler) TriggerJob(w http.ResponseWriter, r *http.Request, id JobId) {
	var request TriggerJobRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TriggerJob(ctx, request.(TriggerJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TriggerJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TriggerJobResponseObject); ok {
		if err := validResponse.VisitTriggerJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ResolveSchedule operation middleware
func (sh *strictHandler) ResolveSchedule(w http.ResponseWriter, r *http.Request) {
	var request ResolveScheduleRequestObject

	var body ResolveScheduleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ResolveSchedule(ctx, request.(ResolveScheduleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ResolveSchedule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ResolveScheduleResponseObject); ok {
		if err := validResponse.VisitResolveScheduleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9Ra32/bOBL+VwjeAdcF7Nj9cYuegXvItr29tL026HbvJRsEY2lsM6FIlRyl8RX+3w8k",
	"ZUm2KEdunDT71prUcPjN8JuPw3zjic5yrVCR5ZNvPAcDGRIa/7/j05N3uDxJ3b+F4hOeAy34gCvIkE+4",
	"SPmAG/xSCIMpn5ApcMBtssAM3BczbTIgPuFF4WfSMndfWTJCzflqNeBvbjApSGh1f0u81dP7M/5eZIJO",
	"HWTVCl8KNMt6Celm8KbVFGdQSOKTp+PxgGdwI7Ii8/8bV0sIRThH49f4OJtZ3L2I9lPiq8SMrtYzm0FW",
	"M+0TwOgcDQn0Y4lBIEwvHAwNQFIgHJLIsI3KgKOCqUSPeTk21VoiKDco0h7IDriEKcqGheaIpYvC7vZJ",
	"FVI6J9YxbVlxwNkcEoyssWrmxFlIknr+2rd6n4MmSufVYnp6iQm5xV754QDzJ/xSoKU20t073sPXtpu3",
	"+2NzrSweJvR3ju6uvQ446StUIbttYkTumINP+KkEl9s3xPyEI/ZRySUzSIVRmDKtmN+L0Oooeop7RTus",
	"3TPWb/W0M9CgQC5JJLY9ZJBQOT8vLCZapf7HiiF+Hr946SlDqPBDnC9aLiVGqwu8yQ1a6wHrwD0OOcy9",
	"F381OOMT/pdRXS5GJYeMPkOYKjL8n1ZxO19xutD6ym3MIO2c4uzogpoYVGz2vEmZPzfBeNoGozZZGNnv",
	"8PA2XI2NbRqMhf+NMdq0A4vxnxOdxtFKkUBI2xirl8jQWpj3IANvvZ7fdndrfnAyuqt1mY5kc3Kl9FeJ",
	"6fyOjPw9dDNzrt8HQV3q6UXPqe4QpIXc0w9LQEVIDeWy94xjJoh8NRHqIjd67vKPu1SQ4hqNH5mBcAXn",
	"PGKQjJjP0VyEgdps5Z7LBFAFyMjnMQ4sIdjaYAPzahNbi99Kkf9GkLToLjwpEEzBxk9GDdzuPZTzYuu/",
	"1dPDVLs+xHoIMdRJzrdUywNRd5Gne0OzF/G2am7JxE2B1ZOTN5Jvw/WOTHjtmdYzmZQfZ3xythswlzyr",
	"QbtwJ6joAtc86X8UhNmtAaipdeUr20n46O+Vt2AMLGOF/Xw14B/whj4VapeI61H78YYuTKH2CvD6o82d",
	"9vt2Y5uZUF173pmX28W7sYlb8qV2PZYTn9BqeY2/lazXKeM2JOi2Iv0AVBiQTIKaFzBHtiZRpg1zzrFN",
	"51pHt7HvSvvw3z+/ulW/Nv3otb27ZM4WBo8+Sdpp0dzBHkniaNNRRpoK9ynI0w3sdgPF3+FyeA2yQEYw",
	"ZzkI44oo3kCWS78LmKNyACUSihSHpZDLjfbrT3i2HEKe85jY/90z3q77x52r1iO/KxzyetAWzBaTwgha",
	"ugOUBUB/QTBojgtatIng+PSEXeFyfTH9D+SWkWbAqnJ3tG7beJS9qfo4LIjy0K8RZXtm0/wro9UQ7BCG",
	"Fs21SJB9FbRgM2EsDRMJ1rLjE+bTibl9mxkkaI/+UB/Wyw9tonNMBywrJImh8xUKWgxYiQ0r9efy6I9w",
	"QsilqF/4vSBkx972qQRyx5odn57wAb9GE1KLPz0aH40d1DpHBbngE/78aHz03KUz0MLjN4LcL+z/Mw8B",
	"dwkL68Ygfy8shXaF9R/WLcqOal1PGTVadK5u3zK72WxbnTv2CPzofXs2HodbmyJ/Pr9xyHMpEu/o6NKG",
	"w1T34DbP3XqHvWRBoye3ikiBJql5u5HLXYt2yly0TApbJnORZWCWJcKsmiAUS0BKNH+zdaI6R3JtI+Fp",
	"9pPKhipa+kWny73g2oVHrIW22kTC3StXrYg9vScXyrIZgfkdLlkpQtkTf+6bragEf9qCPth1lIBf1yHw",
	"U6pzMfom0lU4/BIJ2wF47X+vArDfAal6/JF8f9GmHLc9g9f6ClOXES/CnIMgHJonEUg/aGIzXah0C7pP",
	"3g8GahO3WoZXyEVp5VekWn7vC1vz6eLOTNHzhtBGphpkoWX0w0PyKxLDLadCUVoXEgZEmOVkQ7AWvhuw",
	"K0ahX9AOUOwl5BrNVFvceArZVjD3Gq2t5kYEuTBjuaEm+OTsvIlimMOSBSZXAaZLPd1dH9+6CQ9YHAfb",
	"xPAvIQkNmy69qn1yhctJELlB7w+YwRyBnLAcsOMPr5nFDBSJxP7k1W8ufTc0tAdjsSWYb8S1KqRtIbp1",
	"Q7C09KrFeeI9j5mvuw07Uqe169+KaViXZUDJgmnFLvWUlR2M2DrlUGuRSnYeVnasE6eX7Ajdjd16wxvs",
	"ozdcRnZqDWfl+3SG8/E+RUbj7vTACqNuR8XRXMsKT/LPnt0/yf8XpEi9RYblnE7l4rsaly5/1nTVU7aE",
	"eO7HW+FRv59gCav8eLES/GDg+QFUygRZlgKB86yr9h0UnPHDZeojUiOXlTtBh4ReLWv0alf+Mpos2hGo",
	"uil3CsLhmarV5enFVA8U/+BcGsjg4RPgcXDjKRgSIFl4gQinfosaR5vPBZ3K7k097TuzcHDPQjAmc6rH",
	"wRrngzx1dq239QbZXrXnS2jHboRKNs326WJ3WSsUCbm/tcMKw7s+Vu0UiQ3jfaRineKdgrG26C4U8QOl",
	"8IaGplC7bpPlk9ljrKrbr3kxnsMbYqZQTJStwR9eXh3m1fNW6n3z6bsVmhyK8pUpKu1P3fDjFTtdMsfv",
	"6sdLS49eqSyfWCRW3mX/OQNpy4ZjIxYGbZHtCMYnP/7ni0bY12NoSzo/GJTp0Q6Lk2etqJQFrDssn8OE",
	"g8bl6UO3KZtX2IcXhuN/3P+KLhOFZamwoZ+0mRtlEJnIMkyFk4bYAG7AR2sqte6Yanm9+5w23/LvqSvS",
	"8QcRD3zj6Pq7hUgAyqlpVZUe7E7wShcyZUoTy8FYbNOC84up7T8OId36m5DVVnd485X57NwdZYvmen3+",
	"/Qu2fy6ejEZSJyAX2tLk5fjlmK/OV/8PAAD///k5YLzmMQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
