//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// Defines values for ExecutionStatus.
const (
	ExecutionStatusDelivered  ExecutionStatus = "delivered"
	ExecutionStatusEmitted    ExecutionStatus = "emitted"
	ExecutionStatusFailed     ExecutionStatus = "failed"
	ExecutionStatusInProgress ExecutionStatus = "in_progress"
)

// Valid indicates whether the value is a known member of the ExecutionStatus enum.
func (e ExecutionStatus) Valid() bool {
	switch e {
	case ExecutionStatusDelivered:
		return true
	case ExecutionStatusEmitted:
		return true
	case ExecutionStatusFailed:
		return true
	case ExecutionStatusInProgress:
		return true
	default:
		return false
	}
}

// Defines values for ExecutionTriggerType.
const (
	ExecutionTriggerTypeManual    ExecutionTriggerType = "manual"
	ExecutionTriggerTypeScheduled ExecutionTriggerType = "scheduled"
)

// Valid indicates whether the value is a known member of the ExecutionTriggerType enum.
func (e ExecutionTriggerType) Valid() bool {
	switch e {
	case ExecutionTriggerTypeManual:
		return true
	case ExecutionTriggerTypeScheduled:
		return true
	default:
		return false
	}
}

// Defines values for ListExecutionsParamsStatus.
const (
	ListExecutionsParamsStatusDelivered  ListExecutionsParamsStatus = "delivered"
	ListExecutionsParamsStatusEmitted    ListExecutionsParamsStatus = "emitted"
	ListExecutionsParamsStatusFailed     ListExecutionsParamsStatus = "failed"
	ListExecutionsParamsStatusInProgress ListExecutionsParamsStatus = "in_progress"
)

// Valid indicates whether the value is a known member of the ListExecutionsParamsStatus enum.
func (e ListExecutionsParamsStatus) Valid() bool {
	switch e {
	case ListExecutionsParamsStatusDelivered:
		return true
	case ListExecutionsParamsStatusEmitted:
		return true
	case ListExecutionsParamsStatusFailed:
		return true
	case ListExecutionsParamsStatusInProgress:
		return true
	default:
		return false
	}
}

// Defines values for ListExecutionsParamsTriggerType.
const (
	ListExecutionsParamsTriggerTypeManual    ListExecutionsParamsTriggerType = "manual"
	ListExecutionsParamsTriggerTypeScheduled ListExecutionsParamsTriggerType = "scheduled"
)

// Valid indicates whether the value is a known member of the ListExecutionsParamsTriggerType enum.
func (e ListExecutionsParamsTriggerType) Valid() bool {
	switch e {
	case ListExecutionsParamsTriggerTypeManual:
		return true
	case ListExecutionsParamsTriggerTypeScheduled:
		return true
	default:
		return false
	}
}

// APIKeyInfo defines model for APIKeyInfo.
type APIKeyInfo struct {
	CreatedAt  time.Time          `json:"created_at"`
	Enabled    bool               `json:"enabled"`
	Id         openapi_types.UUID `json:"id"`
	Label      string             `json:"label"`
	LastUsedAt *time.Time         `json:"last_used_at,omitempty"`
	Namespace  string             `json:"namespace"`
}

// CreateAPIKeyRequest defines model for CreateAPIKeyRequest.
type CreateAPIKeyRequest struct {
	Label     string `json:"label"`
	Namespace string `json:"namespace"`
}

// CreateAPIKeyResponse defines model for CreateAPIKeyResponse.
type CreateAPIKeyResponse struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Label     string             `json:"label"`
	Namespace string             `json:"namespace"`

	// Token Plaintext token. Only returned on creation.
	Token string `json:"token"`
}

// CreateJobRequest defines model for CreateJobRequest.
type CreateJobRequest struct {
	Analytics *struct {
		RetentionSeconds *int `json:"retention_seconds,omitempty"`
	} `json:"analytics,omitempty"`
	CronExpression string `json:"cron_expression"`
	Name           string `json:"name"`

	// Tags Key-value tag pairs
	Tags                  *Tag    `json:"tags,omitempty"`
	Timezone              string  `json:"timezone"`
	WebhookSecret         *string `json:"webhook_secret,omitempty"`
	WebhookTimeoutSeconds *int    `json:"webhook_timeout_seconds,omitempty"`
	WebhookUrl            string  `json:"webhook_url"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    string                  `json:"code"`
		Details *map[string]interface{} `json:"details,omitempty"`
		Message string                  `json:"message"`
	} `json:"error"`
}

// Execution defines model for Execution.
type Execution struct {
	AcknowledgedAt *time.Time           `json:"acknowledged_at,omitempty"`
	CreatedAt      time.Time            `json:"created_at"`
	FiredAt        time.Time            `json:"fired_at"`
	Id             openapi_types.UUID   `json:"id"`
	JobId          openapi_types.UUID   `json:"job_id"`
	ScheduledAt    time.Time            `json:"scheduled_at"`
	Status         ExecutionStatus      `json:"status"`
	TriggerType    ExecutionTriggerType `json:"trigger_type"`
}

// ExecutionStatus defines model for Execution.Status.
type ExecutionStatus string

// ExecutionTriggerType defines model for Execution.TriggerType.
type ExecutionTriggerType string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Database *string `json:"database,omitempty"`
	Status   string  `json:"status"`
}

// Job defines model for Job.
type Job struct {
	CreatedAt      time.Time          `json:"created_at"`
	CronExpression string             `json:"cron_expression"`
	Enabled        bool               `json:"enabled"`
	Id             openapi_types.UUID `json:"id"`
	Name           string             `json:"name"`
	Namespace      string             `json:"namespace"`

	// Tags Key-value tag pairs
	Tags       *Tag      `json:"tags,omitempty"`
	Timezone   string    `json:"timezone"`
	UpdatedAt  time.Time `json:"updated_at"`
	WebhookUrl string    `json:"webhook_url"`
}

// JobDetail defines model for JobDetail.
type JobDetail struct {
	CreatedAt        time.Time          `json:"created_at"`
	CronExpression   string             `json:"cron_expression"`
	Enabled          bool               `json:"enabled"`
	Id               openapi_types.UUID `json:"id"`
	Name             string             `json:"name"`
	Namespace        string             `json:"namespace"`
	RecentExecutions *[]Execution       `json:"recent_executions,omitempty"`

	// Tags Key-value tag pairs
	Tags       *Tag      `json:"tags,omitempty"`
	Timezone   string    `json:"timezone"`
	UpdatedAt  time.Time `json:"updated_at"`
	WebhookUrl string    `json:"webhook_url"`
}

// NextRunResponse defines model for NextRunResponse.
type NextRunResponse struct {
	CronExpression string      `json:"cron_expression"`
	NextRunAt      time.Time   `json:"next_run_at"`
	NextRuns       []time.Time `json:"next_runs"`
	Timezone       string      `json:"timezone"`
}

// ResolveScheduleRequest defines model for ResolveScheduleRequest.
type ResolveScheduleRequest struct {
	// Description Natural language schedule or cron expression
	Description string  `json:"description"`
	Timezone    *string `json:"timezone,omitempty"`
}

// ResolveScheduleResponse defines model for ResolveScheduleResponse.
type ResolveScheduleResponse struct {
	CronExpression string      `json:"cron_expression"`
	Description    string      `json:"description"`
	NextRuns       []time.Time `json:"next_runs"`
	Timezone       string      `json:"timezone"`
}

// Tag Key-value tag pairs
type Tag map[string]string

// UpdateJobRequest defines model for UpdateJobRequest.
type UpdateJobRequest struct {
	CronExpression *string `json:"cron_expression,omitempty"`
	Enabled        *bool   `json:"enabled,omitempty"`
	Name           *string `json:"name,omitempty"`

	// Tags Key-value tag pairs
	Tags                  *Tag    `json:"tags,omitempty"`
	Timezone              *string `json:"timezone,omitempty"`
	WebhookSecret         *string `json:"webhook_secret,omitempty"`
	WebhookTimeoutSeconds *int    `json:"webhook_timeout_seconds,omitempty"`
	WebhookUrl            *string `json:"webhook_url,omitempty"`
}

// APIKeyId defines model for APIKeyId.
type APIKeyId = openapi_types.UUID

// ExecutionId defines model for ExecutionId.
type ExecutionId = openapi_types.UUID

// JobId defines model for JobId.
type JobId = openapi_types.UUID

// LimitParam defines model for LimitParam.
type LimitParam = int

// OffsetParam defines model for OffsetParam.
type OffsetParam = int

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// ListAPIKeysParams defines parameters for ListAPIKeys.
type ListAPIKeysParams struct {
	Limit  *LimitParam  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *OffsetParam `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListPendingAckParams defines parameters for ListPendingAck.
type ListPendingAckParams struct {
	Limit *LimitParam         `form:"limit,omitempty" json:"limit,omitempty"`
	JobId *openapi_types.UUID `form:"job_id,omitempty" json:"job_id,omitempty"`
}

// GetHealthParams defines parameters for GetHealth.
type GetHealthParams struct {
	Verbose *bool `form:"verbose,omitempty" json:"verbose,omitempty"`
}

// ListJobsParams defines parameters for ListJobs.
type ListJobsParams struct {
	Limit  *LimitParam  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *OffsetParam `form:"offset,omitempty" json:"offset,omitempty"`

	// Tag Filter by tag (key:value format, repeatable, AND semantics)
	Tag     *[]string `form:"tag,omitempty" json:"tag,omitempty"`
	Enabled *bool     `form:"enabled,omitempty" json:"enabled,omitempty"`

	// Name Substring match on job name
	Name *string `form:"name,omitempty" json:"name,omitempty"`
}

// ListExecutionsParams defines parameters for ListExecutions.
type ListExecutionsParams struct {
	Limit       *LimitParam                      `form:"limit,omitempty" json:"limit,omitempty"`
	Offset      *OffsetParam                     `form:"offset,omitempty" json:"offset,omitempty"`
	Status      *ListExecutionsParamsStatus      `form:"status,omitempty" json:"status,omitempty"`
	TriggerType *ListExecutionsParamsTriggerType `form:"trigger_type,omitempty" json:"trigger_type,omitempty"`
	Since       *time.Time                       `form:"since,omitempty" json:"since,omitempty"`
	Until       *time.Time                       `form:"until,omitempty" json:"until,omitempty"`
}

// ListExecutionsParamsStatus defines parameters for ListExecutions.
type ListExecutionsParamsStatus string

// ListExecutionsParamsTriggerType defines parameters for ListExecutions.
type ListExecutionsParamsTriggerType string

// CreateAPIKeyJSONRequestBody defines body for CreateAPIKey for application/json ContentType.
type CreateAPIKeyJSONRequestBody = CreateAPIKeyRequest

// CreateJobJSONRequestBody defines body for CreateJob for application/json ContentType.
type CreateJobJSONRequestBody = CreateJobRequest

// UpdateJobJSONRequestBody defines body for UpdateJob for application/json ContentType.
type UpdateJobJSONRequestBody = UpdateJobRequest

// ResolveScheduleJSONRequestBody defines body for ResolveSchedule for application/json ContentType.
type ResolveScheduleJSONRequestBody = ResolveScheduleRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List API keys in caller's namespace
	// (GET /api-keys)
	ListAPIKeys(w http.ResponseWriter, r *http.Request, params ListAPIKeysParams)
	// Create a new API key
	// (POST /api-keys)
	CreateAPIKey(w http.ResponseWriter, r *http.Request)
	// Revoke an API key
	// (DELETE /api-keys/{id})
	DeleteAPIKey(w http.ResponseWriter, r *http.Request, id APIKeyId)
	// List unacknowledged completed/failed executions
	// (GET /executions/pending-ack)
	ListPendingAck(w http.ResponseWriter, r *http.Request, params ListPendingAckParams)
	// Get execution detail with delivery attempts
	// (GET /executions/{id})
	GetExecution(w http.ResponseWriter, r *http.Request, id ExecutionId)
	// Acknowledge an execution result
	// (POST /executions/{id}/ack)
	AckExecution(w http.ResponseWriter, r *http.Request, id ExecutionId)
	// Health check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request, params GetHealthParams)
	// List jobs in caller's namespace
	// (GET /jobs)
	ListJobs(w http.ResponseWriter, r *http.Request, params ListJobsParams)
	// Create a new cron job
	// (POST /jobs)
	CreateJob(w http.ResponseWriter, r *http.Request)
	// Delete a job and its data
	// (DELETE /jobs/{id})
	DeleteJob(w http.ResponseWriter, r *http.Request, id JobId)
	// Get job detail with recent executions
	// (GET /jobs/{id})
	GetJob(w http.ResponseWriter, r *http.Request, id JobId)
	// Partial update a job
	// (PATCH /jobs/{id})
	UpdateJob(w http.ResponseWriter, r *http.Request, id JobId)
	// List executions for a job
	// (GET /jobs/{id}/executions)
	ListExecutions(w http.ResponseWriter, r *http.Request, id JobId, params ListExecutionsParams)
	// Get next scheduled run time
	// (GET /jobs/{id}/next-run)
	GetNextRun(w http.ResponseWriter, r *http.Request, id JobId)
	// Pause a job (set enabled=false)
	// (POST /jobs/{id}/pause)
	PauseJob(w http.ResponseWriter, r *http.Request, id JobId)
	// Resume a paused job (set enabled=true)
	// (POST /jobs/{id}/resume)
	ResumeJob(w http.ResponseWriter, r *http.Request, id JobId)
	// Trigger immediate execution
	// (POST /jobs/{id}/trigger)
	TriggerJob(w http.ResponseWriter, r *http.Request, id JobId)
	// Resolve natural language to cron expression
	// (POST /schedules/resolve)
	ResolveSchedule(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAPIKeys operation middleware
func (siw *ServerInterfaceWrapper) ListAPIKeys(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAPIKeysParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAPIKeys(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAPIKey operation middleware
func (siw *ServerInterfaceWrapper) CreateAPIKey(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAPIKey(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAPIKey operation middleware
func (siw *ServerInterfaceWrapper) DeleteAPIKey(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id APIKeyId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAPIKey(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPendingAck operation middleware
func (siw *ServerInterfaceWrapper) ListPendingAck(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPendingAckParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "job_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "job_id", r.URL.Query(), &params.JobId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "job_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "job_id", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPendingAck(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetExecution operation middleware
func (siw *ServerInterfaceWrapper) GetExecution(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ExecutionId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetExecution(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AckExecution operation middleware
func (siw *ServerInterfaceWrapper) AckExecution(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ExecutionId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AckExecution(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetHealthParams

	// ------------- Optional query parameter "verbose" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "verbose", r.URL.Query(), &params.Verbose, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "verbose"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "verbose", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListJobs operation middleware
func (siw *ServerInterfaceWrapper) ListJobs(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListJobsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tag", r.URL.Query(), &params.Tag, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tag"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "enabled" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "enabled", r.URL.Query(), &params.Enabled, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "enabled"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "enabled", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "name", r.URL.Query(), &params.Name, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "name"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListJobs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateJob operation middleware
func (siw *ServerInterfaceWrapper) CreateJob(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateJob(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteJob operation middleware
func (siw *ServerInterfaceWrapper) DeleteJob(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetJob operation middleware
func (siw *ServerInterfaceWrapper) GetJob(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateJob operation middleware
func (siw *ServerInterfaceWrapper) UpdateJob(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListExecutions operation middleware
func (siw *ServerInterfaceWrapper) ListExecutions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListExecutionsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "trigger_type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "trigger_type", r.URL.Query(), &params.TriggerType, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "trigger_type"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "trigger_type", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "since", r.URL.Query(), &params.Since, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "since"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "until" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "until", r.URL.Query(), &params.Until, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "until"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "until", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListExecutions(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNextRun operation middleware
func (siw *ServerInterfaceWrapper) GetNextRun(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNextRun(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PauseJob operation middleware
func (siw *ServerInterfaceWrapper) PauseJob(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PauseJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResumeJob operation middleware
func (siw *ServerInterfaceWrapper) ResumeJob(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResumeJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerJob operation middleware
func (siw *ServerInterfaceWrapper) TriggerJob(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResolveSchedule operation middleware
func (siw *ServerInterfaceWrapper) ResolveSchedule(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResolveSchedule(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api-keys", wrapper.ListAPIKeys)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api-keys", wrapper.CreateAPIKey)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api-keys/{id}", wrapper.DeleteAPIKey)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/executions/pending-ack", wrapper.ListPendingAck)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/executions/{id}", wrapper.GetExecution)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/executions/{id}/ack", wrapper.AckExecution)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/jobs", wrapper.ListJobs)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/jobs", wrapper.CreateJob)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/jobs/{id}", wrapper.DeleteJob)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/jobs/{id}", wrapper.GetJob)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/jobs/{id}", wrapper.UpdateJob)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/jobs/{id}/executions", wrapper.ListExecutions)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/jobs/{id}/next-run", wrapper.GetNextRun)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/jobs/{id}/pause", wrapper.PauseJob)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/jobs/{id}/resume", wrapper.ResumeJob)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/jobs/{id}/trigger", wrapper.TriggerJob)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/schedules/resolve", wrapper.ResolveSchedule)

	return m
}

type ListAPIKeysRequestObject struct {
	Params ListAPIKeysParams
}

type ListAPIKeysResponseObject interface {
	VisitListAPIKeysResponse(w http.ResponseWriter) error
}

type ListAPIKeys200JSONResponse struct {
	Keys []APIKeyInfo `json:"keys"`
}

func (response ListAPIKeys200JSONResponse) VisitListAPIKeysResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAPIKeyRequestObject struct {
	Body *CreateAPIKeyJSONRequestBody
}

type CreateAPIKeyResponseObject interface {
	VisitCreateAPIKeyResponse(w http.ResponseWriter) error
}

type CreateAPIKey201JSONResponse CreateAPIKeyResponse

func (response CreateAPIKey201JSONResponse) VisitCreateAPIKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteAPIKeyRequestObject struct {
	Id APIKeyId `json:"id"`
}

type DeleteAPIKeyResponseObject interface {
	VisitDeleteAPIKeyResponse(w http.ResponseWriter) error
}

type DeleteAPIKey204Response struct {
}

func (response DeleteAPIKey204Response) VisitDeleteAPIKeyResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteAPIKey404JSONResponse Error

func (response DeleteAPIKey404JSONResponse) VisitDeleteAPIKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListPendingAckRequestObject struct {
	Params ListPendingAckParams
}

type ListPendingAckResponseObject interface {
	VisitListPendingAckResponse(w http.ResponseWriter) error
}

type ListPendingAck200JSONResponse struct {
	Executions []Execution `json:"executions"`
}

func (response ListPendingAck200JSONResponse) VisitListPendingAckResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetExecutionRequestObject struct {
	Id ExecutionId `json:"id"`
}

type GetExecutionResponseObject interface {
	VisitGetExecutionResponse(w http.ResponseWriter) error
}

type GetExecution200JSONResponse Execution

func (response GetExecution200JSONResponse) VisitGetExecutionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetExecution404JSONResponse Error

func (response GetExecution404JSONResponse) VisitGetExecutionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type AckExecutionRequestObject struct {
	Id ExecutionId `json:"id"`
}

type AckExecutionResponseObject interface {
	VisitAckExecutionResponse(w http.ResponseWriter) error
}

type AckExecution204Response struct {
}

func (response AckExecution204Response) VisitAckExecutionResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type AckExecution404JSONResponse Error

func (response AckExecution404JSONResponse) VisitAckExecutionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
	Params GetHealthParams
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListJobsRequestObject struct {
	Params ListJobsParams
}

type ListJobsResponseObject interface {
	VisitListJobsResponse(w http.ResponseWriter) error
}

type ListJobs200JSONResponse struct {
	Jobs []Job `json:"jobs"`
}

func (response ListJobs200JSONResponse) VisitListJobsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateJobRequestObject struct {
	Body *CreateJobJSONRequestBody
}

type CreateJobResponseObject interface {
	VisitCreateJobResponse(w http.ResponseWriter) error
}

type CreateJob201JSONResponse JobDetail

func (response CreateJob201JSONResponse) VisitCreateJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateJob422JSONResponse Error

func (response CreateJob422JSONResponse) VisitCreateJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteJobRequestObject struct {
	Id JobId `json:"id"`
}

type DeleteJobResponseObject interface {
	VisitDeleteJobResponse(w http.ResponseWriter) error
}

type DeleteJob204Response struct {
}

func (response DeleteJob204Response) VisitDeleteJobResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteJob404JSONResponse Error

func (response DeleteJob404JSONResponse) VisitDeleteJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetJobRequestObject struct {
	Id JobId `json:"id"`
}

type GetJobResponseObject interface {
	VisitGetJobResponse(w http.ResponseWriter) error
}

type GetJob200JSONResponse JobDetail

func (response GetJob200JSONResponse) VisitGetJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetJob404JSONResponse Error

func (response GetJob404JSONResponse) VisitGetJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateJobRequestObject struct {
	Id   JobId `json:"id"`
	Body *UpdateJobJSONRequestBody
}

type UpdateJobResponseObject interface {
	VisitUpdateJobResponse(w http.ResponseWriter) error
}

type UpdateJob200JSONResponse JobDetail

func (response UpdateJob200JSONResponse) VisitUpdateJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateJob404JSONResponse Error

func (response UpdateJob404JSONResponse) VisitUpdateJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateJob422JSONResponse Error

func (response UpdateJob422JSONResponse) VisitUpdateJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type ListExecutionsRequestObject struct {
	Id     JobId `json:"id"`
	Params ListExecutionsParams
}

type ListExecutionsResponseObject interface {
	VisitListExecutionsResponse(w http.ResponseWriter) error
}

type ListExecutions200JSONResponse struct {
	Executions []Execution `json:"executions"`
}

func (response ListExecutions200JSONResponse) VisitListExecutionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetNextRunRequestObject struct {
	Id JobId `json:"id"`
}

type GetNextRunResponseObject interface {
	VisitGetNextRunResponse(w http.ResponseWriter) error
}

type GetNextRun200JSONResponse NextRunResponse

func (response GetNextRun200JSONResponse) VisitGetNextRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetNextRun404JSONResponse Error

func (response GetNextRun404JSONResponse) VisitGetNextRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PauseJobRequestObject struct {
	Id JobId `json:"id"`
}

type PauseJobResponseObject interface {
	VisitPauseJobResponse(w http.ResponseWriter) error
}

type PauseJob200JSONResponse Job

func (response PauseJob200JSONResponse) VisitPauseJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PauseJob404JSONResponse Error

func (response PauseJob404JSONResponse) VisitPauseJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ResumeJobRequestObject struct {
	Id JobId `json:"id"`
}

type ResumeJobResponseObject interface {
	VisitResumeJobResponse(w http.ResponseWriter) error
}

type ResumeJob200JSONResponse Job

func (response ResumeJob200JSONResponse) VisitResumeJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ResumeJob404JSONResponse Error

func (response ResumeJob404JSONResponse) VisitResumeJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type TriggerJobRequestObject struct {
	Id JobId `json:"id"`
}

type TriggerJobResponseObject interface {
	VisitTriggerJobResponse(w http.ResponseWriter) error
}

type TriggerJob201JSONResponse Execution

func (response TriggerJob201JSONResponse) VisitTriggerJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type TriggerJob404JSONResponse Error

func (response TriggerJob404JSONResponse) VisitTriggerJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type TriggerJob409JSONResponse Error

func (response TriggerJob409JSONResponse) VisitTriggerJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ResolveScheduleRequestObject struct {
	Body *ResolveScheduleJSONRequestBody
}

type ResolveScheduleResponseObject interface {
	VisitResolveScheduleResponse(w http.ResponseWriter) error
}

type ResolveSchedule200JSONResponse ResolveScheduleResponse

func (response ResolveSchedule200JSONResponse) VisitResolveScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ResolveSchedule422JSONResponse Error

func (response ResolveSchedule422JSONResponse) VisitResolveScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List API keys in caller's namespace
	// (GET /api-keys)
	ListAPIKeys(ctx context.Context, request ListAPIKeysRequestObject) (ListAPIKeysResponseObject, error)
	// Create a new API key
	// (POST /api-keys)
	CreateAPIKey(ctx context.Context, request CreateAPIKeyRequestObject) (CreateAPIKeyResponseObject, error)
	// Revoke an API key
	// (DELETE /api-keys/{id})
	DeleteAPIKey(ctx context.Context, request DeleteAPIKeyRequestObject) (DeleteAPIKeyResponseObject, error)
	// List unacknowledged completed/failed executions
	// (GET /executions/pending-ack)
	ListPendingAck(ctx context.Context, request ListPendingAckRequestObject) (ListPendingAckResponseObject, error)
	// Get execution detail with delivery attempts
	// (GET /executions/{id})
	GetExecution(ctx context.Context, request GetExecutionRequestObject) (GetExecutionResponseObject, error)
	// Acknowledge an execution result
	// (POST /executions/{id}/ack)
	AckExecution(ctx context.Context, request AckExecutionRequestObject) (AckExecutionResponseObject, error)
	// Health check
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// List jobs in caller's namespace
	// (GET /jobs)
	ListJobs(ctx context.Context, request ListJobsRequestObject) (ListJobsResponseObject, error)
	// Create a new cron job
	// (POST /jobs)
	CreateJob(ctx context.Context, request CreateJobRequestObject) (CreateJobResponseObject, error)
	// Delete a job and its data
	// (DELETE /jobs/{id})
	DeleteJob(ctx context.Context, request DeleteJobRequestObject) (DeleteJobResponseObject, error)
	// Get job detail with recent executions
	// (GET /jobs/{id})
	GetJob(ctx context.Context, request GetJobRequestObject) (GetJobResponseObject, error)
	// Partial update a job
	// (PATCH /jobs/{id})
	UpdateJob(ctx context.Context, request UpdateJobRequestObject) (UpdateJobResponseObject, error)
	// List executions for a job
	// (GET /jobs/{id}/executions)
	ListExecutions(ctx context.Context, request ListExecutionsRequestObject) (ListExecutionsResponseObject, error)
	// Get next scheduled run time
	// (GET /jobs/{id}/next-run)
	GetNextRun(ctx context.Context, request GetNextRunRequestObject) (GetNextRunResponseObject, error)
	// Pause a job (set enabled=false)
	// (POST /jobs/{id}/pause)
	PauseJob(ctx context.Context, request PauseJobRequestObject) (PauseJobResponseObject, error)
	// Resume a paused job (set enabled=true)
	// (POST /jobs/{id}/resume)
	ResumeJob(ctx context.Context, request ResumeJobRequestObject) (ResumeJobResponseObject, error)
	// Trigger immediate execution
	// (POST /jobs/{id}/trigger)
	TriggerJob(ctx context.Context, request TriggerJobRequestObject) (TriggerJobResponseObject, error)
	// Resolve natural language to cron expression
	// (POST /schedules/resolve)
	ResolveSchedule(ctx context.Context, request ResolveScheduleRequestObject) (ResolveScheduleResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListAPIKeys operation middleware
func (sh *strictHandler) ListAPIKeys(w http.ResponseWriter, r *http.Request, params ListAPIKeysParams) {
	var request ListAPIKeysRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAPIKeys(ctx, request.(ListAPIKeysRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAPIKeys")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAPIKeysResponseObject); ok {
		if err := validResponse.VisitListAPIKeysResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateAPIKey operation middleware
func (sh *strictHandler) CreateAPIKey(w http.ResponseWriter, r *http.Request) {
	var request CreateAPIKeyRequestObject

	var body CreateAPIKeyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAPIKey(ctx, request.(CreateAPIKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAPIKey")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateAPIKeyResponseObject); ok {
		if err := validResponse.VisitCreateAPIKeyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteAPIKey operation middleware
func (sh *strictHandler) DeleteAPIKey(w http.ResponseWriter, r *http.Request, id APIKeyId) {
	var request DeleteAPIKeyRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteAPIKey(ctx, request.(DeleteAPIKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteAPIKey")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteAPIKeyResponseObject); ok {
		if err := validResponse.VisitDeleteAPIKeyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListPendingAck operation middleware
func (sh *strictHandler) ListPendingAck(w http.ResponseWriter, r *http.Request, params ListPendingAckParams) {
	var request ListPendingAckRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListPendingAck(ctx, request.(ListPendingAckRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPendingAck")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListPendingAckResponseObject); ok {
		if err := validResponse.VisitListPendingAckResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetExecution operation middleware
func (sh *strictHandler) GetExecution(w http.ResponseWriter, r *http.Request, id ExecutionId) {
	var request GetExecutionRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetExecution(ctx, request.(GetExecutionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetExecution")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetExecutionResponseObject); ok {
		if err := validResponse.VisitGetExecutionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AckExecution operation middleware
func (sh *strictHandler) AckExecution(w http.ResponseWriter, r *http.Request, id ExecutionId) {
	var request AckExecutionRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AckExecution(ctx, request.(AckExecutionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AckExecution")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AckExecutionResponseObject); ok {
		if err := validResponse.VisitAckExecutionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request, params GetHealthParams) {
	var request GetHealthRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListJobs operation middleware
func (sh *strictHandler) ListJobs(w http.ResponseWriter, r *http.Request, params ListJobsParams) {
	var request ListJobsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListJobs(ctx, request.(ListJobsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListJobs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListJobsResponseObject); ok {
		if err := validResponse.VisitListJobsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateJob operation middleware
func (sh *strictHandler) CreateJob(w http.ResponseWriter, r *http.Request) {
	var request CreateJobRequestObject

	var body CreateJobJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateJob(ctx, request.(CreateJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateJobResponseObject); ok {
		if err := validResponse.VisitCreateJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteJob operation middleware
func (sh *strictHandler) DeleteJob(w http.ResponseWriter, r *http.Request, id JobId) {
	var request DeleteJobRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteJob(ctx, request.(DeleteJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteJobResponseObject); ok {
		if err := validResponse.VisitDeleteJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetJob operation middleware
func (sh *strictHandler) GetJob(w http.ResponseWriter, r *http.Request, id JobId) {
	var request GetJobRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetJob(ctx, request.(GetJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetJobResponseObject); ok {
		if err := validResponse.VisitGetJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateJob operation middleware
func (sh *strictHandler) UpdateJob(w http.ResponseWriter, r *http.Request, id JobId) {
	var request UpdateJobRequestObject

	request.Id = id

	var body UpdateJobJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateJob(ctx, request.(UpdateJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateJobResponseObject); ok {
		if err := validResponse.VisitUpdateJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListExecutions operation middleware
func (sh *strictHandler) ListExecutions(w http.ResponseWriter, r *http.Request, id JobId, params ListExecutionsParams) {
	var request ListExecutionsRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListExecutions(ctx, request.(ListExecutionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListExecutions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListExecutionsResponseObject); ok {
		if err := validResponse.VisitListExecutionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetNextRun operation middleware
func (sh *strictHandler) GetNextRun(w http.ResponseWriter, r *http.Request, id JobId) {
	var request GetNextRunRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetNextRun(ctx, request.(GetNextRunRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetNextRun")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetNextRunResponseObject); ok {
		if err := validResponse.VisitGetNextRunResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PauseJob operation middleware
func (sh *strictHandler) PauseJob(w http.ResponseWriter, r *http.Request, id JobId) {
	var request PauseJobRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PauseJob(ctx, request.(PauseJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PauseJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PauseJobResponseObject); ok {
		if err := validResponse.VisitPauseJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ResumeJob operation middleware
func (sh *strictHandler) ResumeJob(w http.ResponseWriter, r *http.Request, id JobId) {
	var request ResumeJobRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ResumeJob(ctx, request.(ResumeJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ResumeJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ResumeJobResponseObject); ok {
		if err := validResponse.VisitResumeJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TriggerJob operation middleware
func (sh *strictHandler) TriggerJob(w http.ResponseWriter, r *http.Request, id JobId) {
	var request TriggerJobRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TriggerJob(ctx, request.(TriggerJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TriggerJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TriggerJobResponseObject); ok {
		if err := validResponse.VisitTriggerJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ResolveSchedule operation middleware
func (sh *strictHandler) ResolveSchedule(w http.ResponseWriter, r *http.Request) {
	var request ResolveScheduleRequestObject

	var body ResolveScheduleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ResolveSchedule(ctx, request.(ResolveScheduleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ResolveSchedule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ResolveScheduleResponseObject); ok {
		if err := validResponse.VisitResolveScheduleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3Fptc9u4Ef4rGLQzzc1IlvLSm1Qz/eBL0quTNPHkcv2S83hW5EqCBQIMADpWM/rvHQB8FUGaiiXb7Tdb",
	"ALG7z+4+u1jyO41kkkqBwmg6+05TUJCgQeX+Oz0/e4ebs9j+zQSd0RTMio6ogATpjLKYjqjCrxlTGNOZ",
	"URmOqI5WmIB9YiFVAobOaJa5nWaT2qe0UUws6XY7om9uMMoMk+J4It7K+fEOf88SZs4tZKWErxmqTSWC",
	"2x20fmqMC8i4obOn0+mIJnDDkixx/01LEUwYXKJyMj4uFhr7hUi3JSwldOi22Fl3slhIFwBKpqgMQ7cW",
	"KQSD8aWFoQZIDAbHhiXYRmVEUcCco8M8X5tLyRGEXWTxAGRHlMMcee2E+oo2l5nu10lknFslCp+2TrHA",
	"6RQiDMjY1mPiiw+San+hW2XnqI7SRSlMzq8wMlbYK7fsYf6EXzPUpo10t8V76NpW83Z9dCqFxsO4/s7e",
	"7bN1RI1co/DRrSPFUsscdEbPOdjYvjHEbTghHwXfEIUmUwJjIgVxtjApToJZPMjbXvZAX7+V805HgwC+",
	"MSzS7SWFBoXV81JjJEXsfiwZ4ufpi5eOMpjwP4T5oqVSpKS4xJtUodYOsA7cw5DD0mnxZ4ULOqN/mlTl",
	"YpJzyOQz+K0swf9IET7nG85XUq6tYQpN7xZ7jsxMHYOSzZ7XKfPnOhhP22BUR2aKD0se2oarZljzwJD7",
	"3yglVduxGP45knEYrRgNMK5ra5WIBLWG5QAycKdX+9vq7uz3SgatKsp0IJqjtZDfOMbLOzLyj9DNwqp+",
	"DIK6kvPLgVttEsQZ31MPbcBkPjSEjd4vFBNmjKsmTFymSi5t/FEbCpxdo3IrC2C24FwEDjSKLZeoLv1C",
	"dWypno0EEBnwwOMhDswh2DGwhnlpxI7wWynynwjcrLoLTwwG5qDDmVEB129Dvi8k/62cH6baDSHWQzRD",
	"neR8S7U8EHVnabw3NHsRb6vm5kxcb7AGcnIj+Bqqd0TCa8e0jsk4/7igsy/9gNng2Y7ahTtCYS6x4En3",
	"IzOY3OqAilq3rrKd+Yf+WmoLSsEmVNgvtiP6AW/Mp0z0NXEDaj/emEuVib0cXDzUtHTYsw0zEya6bO6N",
	"y93iXTPilnipVA/FxCfUkl/jbznrdbZxjRZ0tyP9ACZTwAkHscxgiaQgUSIVscqRpnKt1K3ZXfY+9PfP",
	"r27tX+t6DDLvLpGzg8GjD5J2WNQt2CNILG1ayohjZh8Fft7Arh8o+g4342vgGRIDS5ICU7aI4g0kKXdW",
	"wBKFBSjikMU4zhu5VEknf0aTzRjSlIaa/d8d4/XdP+5ctR75XeGQ14N2w6wxyhQzG5tAiQf0FwSF6jQz",
	"qzYRnJ6fkTVuiovpvyDVxEgCpCx3J8XYxqHsjqrSYWVM6uc1LB/PNI9/paQYgx7DWKO6ZhGSb8ysyIIp",
	"bcYRB63J6Rlx4USs3WoBEeqTP8SHQvxYRzLFeESSjBs2trpCZlYjkmND8v5zc/KHzxBjQ9QJfs8MklN3",
	"9jkHY9OanJ6f0RG9RuVDiz49mZ5MLdQyRQEpozP6/GR68tyGM5iVw28CqRPs/ll6h9uAhWIwSN8zbfy4",
	"QrsHqxFlR7WutkxqIzpbt2/ZXR+2bS8se3h+dLo9m079rU0Yl5/fKaQpZ5FTdHKlfTJVM7hm3hUWDmoL",
	"ajO5baAVqJOaOzdwuWvRTh6LmnCm82DOkgTUJkeYlBuYIBFwjuovugpUq0gqdcA99XlSPlBFbX6R8WYv",
	"uPrwCI3Qtk0k7L1y2/LY0yOpkJfNAMzvcEPyJpQ8cXlfH0VF+NMO9P5cSwn4rXCB21LmxeQ7i7c++Tka",
	"bDvgtfu9dMB+CVLO+APx/qJNOdY8hddyjbGNiBd+z0EQ9sOTAKQfpCELmYl4B7pPTg8Coolb1YZPUhQx",
	"E8sxROtedjn3+06j9V0JJjSfb9ylh71bOCz33PVi0ktAtcOH0FAONYFo3clEmajPlYhVz0Z4PPETEFIT",
	"uevxIleCrv4VTWXXvo6uv6y6s38GQt+Gr1wkfkj44En4K5rKH7lSvg0pWgcCxmCSmrCzJnluhmvLabQ+",
	"mscC7HZaC7sHR7amjOW4CmSF2t4IHZorN03ri3g/b2uDF2Kqa1RzqbFBVbs3gKPG/s5wMICW37FpdON0",
	"9uWijpzfQ6IVRmsP05Wc9/eXb+2Ge2wuR7uh9w/GDSoy37hb4ZM1bmb+kuhLxYgoTBGMvZiNyOmH10Rj",
	"AsKwSP/kbo8pd28T/Hg95FsDy4ZfyzLQvsjt3LC12biu32rSWeSqaV1P6LSs/i2be7kkAROtiBTkSs5J",
	"PgEMycmXWkKOVDqLwBlUNP10sL9cugOHFEobkZ0V0p7yY3261fGYTXpt9nDPHXo1zg2jWbTljtifPTs+",
	"sf8bOIvdiQTzPZ2dv5sKXtn4KehqYNvv/bkfb/mPYoaVRC/l4auh14OA4wcQMWFGkxgMWM26at9BwZne",
	"X6Q+ot7uqlTHd3X+XUejBXfDnGjV9kA5jbyTEw7PVK0p6SCmuif/e+ViTwb3HwCPgxvPQRkGnPg3eD7r",
	"d6hx0rzVdnZ2b6ptPxiFoyM3gqE2p3y5XuF8kE8FuuTtvMNvSx34JUGHNUxEGB6A9LwF6jotE4bx/U/7",
	"/52pVCHe2TBWJ9oLRTihBN6YscpE320yf+X8GKvq7tvwEM/hjSEqE4Tlo/UHL68W8/L1cOx0c+G745oU",
	"svwtbbC1P7fLj7fZ6WpznFUP31o69PLO8olGQ/K77N8XwHU+sK/5QqHOkh5nfHLr/3ve8HY9hrG+1YNA",
	"Hh5tt9j2rOWVvIB1u+Wz33BQvzy976Fv/Qp7/43h9G/Hl2gjkWkSM+3nSc3YyJ1IWJJgzGxriDXgRnRS",
	"UKm2aSr5dX+e1r+FOdJUpOODonu+cXR99xNwQL41LqvSvd0JXsmMx0RIQ1JQGtu0YPUiYvfjKiNb31Rt",
	"d6bDza80vlzYVNaorov8d1+AuM8tZpMJlxHwldRm9nL6ckq3F9v/BgAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
