//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for ExecutionStatus.
const (
	ExecutionStatusDelivered  ExecutionStatus = "delivered"
	ExecutionStatusEmitted    ExecutionStatus = "emitted"
	ExecutionStatusFailed     ExecutionStatus = "failed"
	ExecutionStatusInProgress ExecutionStatus = "in_progress"
)

// Valid indicates whether the value is a known member of the ExecutionStatus enum.
func (e ExecutionStatus) Valid() bool {
	switch e {
	case ExecutionStatusDelivered:
		return true
	case ExecutionStatusEmitted:
		return true
	case ExecutionStatusFailed:
		return true
	case ExecutionStatusInProgress:
		return true
	default:
		return false
	}
}

// Defines values for ExecutionTriggerType.
const (
	ExecutionTriggerTypeManual    ExecutionTriggerType = "manual"
	ExecutionTriggerTypeScheduled ExecutionTriggerType = "scheduled"
)

// Valid indicates whether the value is a known member of the ExecutionTriggerType enum.
func (e ExecutionTriggerType) Valid() bool {
	switch e {
	case ExecutionTriggerTypeManual:
		return true
	case ExecutionTriggerTypeScheduled:
		return true
	default:
		return false
	}
}

// Defines values for ListExecutionsParamsStatus.
const (
	ListExecutionsParamsStatusDelivered  ListExecutionsParamsStatus = "delivered"
	ListExecutionsParamsStatusEmitted    ListExecutionsParamsStatus = "emitted"
	ListExecutionsParamsStatusFailed     ListExecutionsParamsStatus = "failed"
	ListExecutionsParamsStatusInProgress ListExecutionsParamsStatus = "in_progress"
)

// Valid indicates whether the value is a known member of the ListExecutionsParamsStatus enum.
func (e ListExecutionsParamsStatus) Valid() bool {
	switch e {
	case ListExecutionsParamsStatusDelivered:
		return true
	case ListExecutionsParamsStatusEmitted:
		return true
	case ListExecutionsParamsStatusFailed:
		return true
	case ListExecutionsParamsStatusInProgress:
		return true
	default:
		return false
	}
}

// Defines values for ListExecutionsParamsTriggerType.
const (
	ListExecutionsParamsTriggerTypeManual    ListExecutionsParamsTriggerType = "manual"
	ListExecutionsParamsTriggerTypeScheduled ListExecutionsParamsTriggerType = "scheduled"
)

// Valid indicates whether the value is a known member of the ListExecutionsParamsTriggerType enum.
func (e ListExecutionsParamsTriggerType) Valid() bool {
	switch e {
	case ListExecutionsParamsTriggerTypeManual:
		return true
	case ListExecutionsParamsTriggerTypeScheduled:
		return true
	default:
		return false
	}
}

// APIKeyInfo defines model for APIKeyInfo.
type APIKeyInfo struct {
	CreatedAt  time.Time          `json:"created_at"`
	Enabled    bool               `json:"enabled"`
	Id         openapi_types.UUID `json:"id"`
	Label      string             `json:"label"`
	LastUsedAt *time.Time         `json:"last_used_at,omitempty"`
	Namespace  string             `json:"namespace"`
}

// CreateAPIKeyRequest defines model for CreateAPIKeyRequest.
type CreateAPIKeyRequest struct {
	Label     string `json:"label"`
	Namespace string `json:"namespace"`
}

// CreateAPIKeyResponse defines model for CreateAPIKeyResponse.
type CreateAPIKeyResponse struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Label     string             `json:"label"`
	Namespace string             `json:"namespace"`

	// Token Plaintext token. Only returned on creation.
	Token string `json:"token"`
}

// CreateJobRequest defines model for CreateJobRequest.
type CreateJobRequest struct {
	Analytics *struct {
		RetentionSeconds *int `json:"retention_seconds,omitempty"`
	} `json:"analytics,omitempty"`
	CronExpression string `json:"cron_expression"`
	Name           string `json:"name"`

	// Tags Key-value tag pairs
	Tags                  *Tag    `json:"tags,omitempty"`
	Timezone              string  `json:"timezone"`
	WebhookSecret         *string `json:"webhook_secret,omitempty"`
	WebhookTimeoutSeconds *int    `json:"webhook_timeout_seconds,omitempty"`
	WebhookUrl            string  `json:"webhook_url"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    string                  `json:"code"`
		Details *map[string]interface{} `json:"details,omitempty"`
		Message string                  `json:"message"`
	} `json:"error"`
}

// Execution defines model for Execution.
type Execution struct {
	AcknowledgedAt *time.Time           `json:"acknowledged_at,omitempty"`
	CreatedAt      time.Time            `json:"created_at"`
	FiredAt        time.Time            `json:"fired_at"`
	Id             openapi_types.UUID   `json:"id"`
	JobId          openapi_types.UUID   `json:"job_id"`
	ScheduledAt    time.Time            `json:"scheduled_at"`
	Status         ExecutionStatus      `json:"status"`
	TriggerType    ExecutionTriggerType `json:"trigger_type"`
}

// ExecutionStatus defines model for Execution.Status.
type ExecutionStatus string

// ExecutionTriggerType defines model for Execution.TriggerType.
type ExecutionTriggerType string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Database *string `json:"database,omitempty"`
	Status   string  `json:"status"`
}

// Job defines model for Job.
type Job struct {
	CreatedAt      time.Time          `json:"created_at"`
	CronExpression string             `json:"cron_expression"`
	Enabled        bool               `json:"enabled"`
	Id             openapi_types.UUID `json:"id"`
	Name           string             `json:"name"`
	Namespace      string             `json:"namespace"`

	// Tags Key-value tag pairs
	Tags       *Tag      `json:"tags,omitempty"`
	Timezone   string    `json:"timezone"`
	UpdatedAt  time.Time `json:"updated_at"`
	WebhookUrl string    `json:"webhook_url"`
}

// JobDetail defines model for JobDetail.
type JobDetail struct {
	CreatedAt        time.Time          `json:"created_at"`
	CronExpression   string             `json:"cron_expression"`
	Enabled          bool               `json:"enabled"`
	Id               openapi_types.UUID `json:"id"`
	Name             string             `json:"name"`
	Namespace        string             `json:"namespace"`
	RecentExecutions *[]Execution       `json:"recent_executions,omitempty"`

	// Tags Key-value tag pairs
	Tags       *Tag      `json:"tags,omitempty"`
	Timezone   string    `json:"timezone"`
	UpdatedAt  time.Time `json:"updated_at"`
	WebhookUrl string    `json:"webhook_url"`
}

// NextRunResponse defines model for NextRunResponse.
type NextRunResponse struct {
	CronExpression string      `json:"cron_expression"`
	NextRunAt      time.Time   `json:"next_run_at"`
	NextRuns       []time.Time `json:"next_runs"`
	Timezone       string      `json:"timezone"`
}

// ResolveScheduleRequest defines model for ResolveScheduleRequest.
type ResolveScheduleRequest struct {
	// Description Natural language schedule or cron expression
	Description string  `json:"description"`
	Timezone    *string `json:"timezone,omitempty"`
}

// ResolveScheduleResponse defines model for ResolveScheduleResponse.
type ResolveScheduleResponse struct {
	CronExpression string      `json:"cron_expression"`
	Description    string      `json:"description"`
	NextRuns       []time.Time `json:"next_runs"`
	Timezone       string      `json:"timezone"`
}

// Tag Key-value tag pairs
type Tag map[string]string

// UpdateJobRequest defines model for UpdateJobRequest.
type UpdateJobRequest struct {
	CronExpression *string `json:"cron_expression,omitempty"`
	Enabled        *bool   `json:"enabled,omitempty"`
	Name           *string `json:"name,omitempty"`

	// Tags Key-value tag pairs
	Tags                  *Tag    `json:"tags,omitempty"`
	Timezone              *string `json:"timezone,omitempty"`
	WebhookSecret         *string `json:"webhook_secret,omitempty"`
	WebhookTimeoutSeconds *int    `json:"webhook_timeout_seconds,omitempty"`
	WebhookUrl            *string `json:"webhook_url,omitempty"`
}

// APIKeyId defines model for APIKeyId.
type APIKeyId = openapi_types.UUID

// ExecutionId defines model for ExecutionId.
type ExecutionId = openapi_types.UUID

// JobId defines model for JobId.
type JobId = openapi_types.UUID

// LimitParam defines model for LimitParam.
type LimitParam = int

// OffsetParam defines model for OffsetParam.
type OffsetParam = int

// ListAPIKeysParams defines parameters for ListAPIKeys.
type ListAPIKeysParams struct {
	Limit  *LimitParam  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *OffsetParam `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListPendingAckParams defines parameters for ListPendingAck.
type ListPendingAckParams struct {
	Limit *LimitParam         `form:"limit,omitempty" json:"limit,omitempty"`
	JobId *openapi_types.UUID `form:"job_id,omitempty" json:"job_id,omitempty"`
}

// GetHealthParams defines parameters for GetHealth.
type GetHealthParams struct {
	Verbose *bool `form:"verbose,omitempty" json:"verbose,omitempty"`
}

// ListJobsParams defines parameters for ListJobs.
type ListJobsParams struct {
	Limit  *LimitParam  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *OffsetParam `form:"offset,omitempty" json:"offset,omitempty"`

	// Tag Filter by tag (key:value format, repeatable, AND semantics)
	Tag     *[]string `form:"tag,omitempty" json:"tag,omitempty"`
	Enabled *bool     `form:"enabled,omitempty" json:"enabled,omitempty"`

	// Name Substring match on job name
	Name *string `form:"name,omitempty" json:"name,omitempty"`
}

// ListExecutionsParams defines parameters for ListExecutions.
type ListExecutionsParams struct {
	Limit       *LimitParam                      `form:"limit,omitempty" json:"limit,omitempty"`
	Offset      *OffsetParam                     `form:"offset,omitempty" json:"offset,omitempty"`
	Status      *ListExecutionsParamsStatus      `form:"status,omitempty" json:"status,omitempty"`
	TriggerType *ListExecutionsParamsTriggerType `form:"trigger_type,omitempty" json:"trigger_type,omitempty"`
	Since       *time.Time                       `form:"since,omitempty" json:"since,omitempty"`
	Until       *time.Time                       `form:"until,omitempty" json:"until,omitempty"`
}

// ListExecutionsParamsStatus defines parameters for ListExecutions.
type ListExecutionsParamsStatus string

// ListExecutionsParamsTriggerType defines parameters for ListExecutions.
type ListExecutionsParamsTriggerType string

// CreateAPIKeyJSONRequestBody defines body for CreateAPIKey for application/json ContentType.
type CreateAPIKeyJSONRequestBody = CreateAPIKeyRequest

// CreateJobJSONRequestBody defines body for CreateJob for application/json ContentType.
type CreateJobJSONRequestBody = CreateJobRequest

// UpdateJobJSONRequestBody defines body for UpdateJob for application/json ContentType.
type UpdateJobJSONRequestBody = UpdateJobRequest

// ResolveScheduleJSONRequestBody defines body for ResolveSchedule for application/json ContentType.
type ResolveScheduleJSONRequestBody = ResolveScheduleRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List API keys in caller's namespace
	// (GET /api-keys)
	ListAPIKeys(w http.ResponseWriter, r *http.Request, params ListAPIKeysParams)
	// Create a new API key
	// (POST /api-keys)
	CreateAPIKey(w http.ResponseWriter, r *http.Request)
	// Revoke an API key
	// (DELETE /api-keys/{id})
	DeleteAPIKey(w http.ResponseWriter, r *http.Request, id APIKeyId)
	// List unacknowledged completed/failed executions
	// (GET /executions/pending-ack)
	ListPendingAck(w http.ResponseWriter, r *http.Request, params ListPendingAckParams)
	// Get execution detail with delivery attempts
	// (GET /executions/{id})
	GetExecution(w http.ResponseWriter, r *http.Request, id ExecutionId)
	// Acknowledge an execution result
	// (POST /executions/{id}/ack)
	AckExecution(w http.ResponseWriter, r *http.Request, id ExecutionId)
	// Health check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request, params GetHealthParams)
	// List jobs in caller's namespace
	// (GET /jobs)
	ListJobs(w http.ResponseWriter, r *http.Request, params ListJobsParams)
	// Create a new cron job
	// (POST /jobs)
	CreateJob(w http.ResponseWriter, r *http.Request)
	// Delete a job and its data
	// (DELETE /jobs/{id})
	DeleteJob(w http.ResponseWriter, r *http.Request, id JobId)
	// Get job detail with recent executions
	// (GET /jobs/{id})
	GetJob(w http.ResponseWriter, r *http.Request, id JobId)
	// Partial update a job
	// (PATCH /jobs/{id})
	UpdateJob(w http.ResponseWriter, r *http.Request, id JobId)
	// List executions for a job
	// (GET /jobs/{id}/executions)
	ListExecutions(w http.ResponseWriter, r *http.Request, id JobId, params ListExecutionsParams)
	// Get next scheduled run time
	// (GET /jobs/{id}/next-run)
	GetNextRun(w http.ResponseWriter, r *http.Request, id JobId)
	// Pause a job (set enabled=false)
	// (POST /jobs/{id}/pause)
	PauseJob(w http.ResponseWriter, r *http.Request, id JobId)
	// Resume a paused job (set enabled=true)
	// (POST /jobs/{id}/resume)
	ResumeJob(w http.ResponseWriter, r *http.Request, id JobId)
	// Trigger immediate execution
	// (POST /jobs/{id}/trigger)
	TriggerJob(w http.ResponseWriter, r *http.Request, id JobId)
	// Resolve natural language to cron expression
	// (POST /schedules/resolve)
	ResolveSchedule(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAPIKeys operation middleware
func (siw *ServerInterfaceWrapper) ListAPIKeys(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAPIKeysParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAPIKeys(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAPIKey operation middleware
func (siw *ServerInterfaceWrapper) CreateAPIKey(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAPIKey(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAPIKey operation middleware
func (siw *ServerInterfaceWrapper) DeleteAPIKey(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id APIKeyId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAPIKey(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPendingAck operation middleware
func (siw *ServerInterfaceWrapper) ListPendingAck(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPendingAckParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "job_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "job_id", r.URL.Query(), &params.JobId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "job_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPendingAck(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetExecution operation middleware
func (siw *ServerInterfaceWrapper) GetExecution(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ExecutionId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetExecution(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AckExecution operation middleware
func (siw *ServerInterfaceWrapper) AckExecution(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ExecutionId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AckExecution(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetHealthParams

	// ------------- Optional query parameter "verbose" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "verbose", r.URL.Query(), &params.Verbose, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "verbose", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListJobs operation middleware
func (siw *ServerInterfaceWrapper) ListJobs(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListJobsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tag", r.URL.Query(), &params.Tag, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		return
	}

	// ------------- Optional query parameter "enabled" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "enabled", r.URL.Query(), &params.Enabled, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "enabled", Err: err})
		return
	}

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "name", r.URL.Query(), &params.Name, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListJobs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateJob operation middleware
func (siw *ServerInterfaceWrapper) CreateJob(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateJob(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteJob operation middleware
func (siw *ServerInterfaceWrapper) DeleteJob(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetJob operation middleware
func (siw *ServerInterfaceWrapper) GetJob(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateJob operation middleware
func (siw *ServerInterfaceWrapper) UpdateJob(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListExecutions operation middleware
func (siw *ServerInterfaceWrapper) ListExecutions(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListExecutionsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "trigger_type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "trigger_type", r.URL.Query(), &params.TriggerType, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "trigger_type", Err: err})
		return
	}

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "since", r.URL.Query(), &params.Since, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		return
	}

	// ------------- Optional query parameter "until" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "until", r.URL.Query(), &params.Until, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "until", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListExecutions(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNextRun operation middleware
func (siw *ServerInterfaceWrapper) GetNextRun(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNextRun(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PauseJob operation middleware
func (siw *ServerInterfaceWrapper) PauseJob(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PauseJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResumeJob operation middleware
func (siw *ServerInterfaceWrapper) ResumeJob(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResumeJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerJob operation middleware
func (siw *ServerInterfaceWrapper) TriggerJob(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResolveSchedule operation middleware
func (siw *ServerInterfaceWrapper) ResolveSchedule(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResolveSchedule(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api-keys", wrapper.ListAPIKeys)
	m.HandleFunc("POST "+options.BaseURL+"/api-keys", wrapper.CreateAPIKey)
	m.HandleFunc("DELETE "+options.BaseURL+"/api-keys/{id}", wrapper.DeleteAPIKey)
	m.HandleFunc("GET "+options.BaseURL+"/executions/pending-ack", wrapper.ListPendingAck)
	m.HandleFunc("GET "+options.BaseURL+"/executions/{id}", wrapper.GetExecution)
	m.HandleFunc("POST "+options.BaseURL+"/executions/{id}/ack", wrapper.AckExecution)
	m.HandleFunc("GET "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc("GET "+options.BaseURL+"/jobs", wrapper.ListJobs)
	m.HandleFunc("POST "+options.BaseURL+"/jobs", wrapper.CreateJob)
	m.HandleFunc("DELETE "+options.BaseURL+"/jobs/{id}", wrapper.DeleteJob)
	m.HandleFunc("GET "+options.BaseURL+"/jobs/{id}", wrapper.GetJob)
	m.HandleFunc("PATCH "+options.BaseURL+"/jobs/{id}", wrapper.UpdateJob)
	m.HandleFunc("GET "+options.BaseURL+"/jobs/{id}/executions", wrapper.ListExecutions)
	m.HandleFunc("GET "+options.BaseURL+"/jobs/{id}/next-run", wrapper.GetNextRun)
	m.HandleFunc("POST "+options.BaseURL+"/jobs/{id}/pause", wrapper.PauseJob)
	m.HandleFunc("POST "+options.BaseURL+"/jobs/{id}/resume", wrapper.ResumeJob)
	m.HandleFunc("POST "+options.BaseURL+"/jobs/{id}/trigger", wrapper.TriggerJob)
	m.HandleFunc("POST "+options.BaseURL+"/schedules/resolve", wrapper.ResolveSchedule)

	return m
}

type ListAPIKeysRequestObject struct {
	Params ListAPIKeysParams
}

type ListAPIKeysResponseObject interface {
	VisitListAPIKeysResponse(w http.ResponseWriter) error
}

type ListAPIKeys200JSONResponse struct {
	Keys []APIKeyInfo `json:"keys"`
}

func (response ListAPIKeys200JSONResponse) VisitListAPIKeysResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateAPIKeyRequestObject struct {
	Body *CreateAPIKeyJSONRequestBody
}

type CreateAPIKeyResponseObject interface {
	VisitCreateAPIKeyResponse(w http.ResponseWriter) error
}

type CreateAPIKey201JSONResponse CreateAPIKeyResponse

func (response CreateAPIKey201JSONResponse) VisitCreateAPIKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAPIKeyRequestObject struct {
	Id APIKeyId `json:"id"`
}

type DeleteAPIKeyResponseObject interface {
	VisitDeleteAPIKeyResponse(w http.ResponseWriter) error
}

type DeleteAPIKey204Response struct {
}

func (response DeleteAPIKey204Response) VisitDeleteAPIKeyResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteAPIKey404JSONResponse Error

func (response DeleteAPIKey404JSONResponse) VisitDeleteAPIKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ListPendingAckRequestObject struct {
	Params ListPendingAckParams
}

type ListPendingAckResponseObject interface {
	VisitListPendingAckResponse(w http.ResponseWriter) error
}

type ListPendingAck200JSONResponse struct {
	Executions []Execution `json:"executions"`
}

func (response ListPendingAck200JSONResponse) VisitListPendingAckResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetExecutionRequestObject struct {
	Id ExecutionId `json:"id"`
}

type GetExecutionResponseObject interface {
	VisitGetExecutionResponse(w http.ResponseWriter) error
}

type GetExecution200JSONResponse Execution

func (response GetExecution200JSONResponse) VisitGetExecutionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetExecution404JSONResponse Error

func (response GetExecution404JSONResponse) VisitGetExecutionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type AckExecutionRequestObject struct {
	Id ExecutionId `json:"id"`
}

type AckExecutionResponseObject interface {
	VisitAckExecutionResponse(w http.ResponseWriter) error
}

type AckExecution204Response struct {
}

func (response AckExecution204Response) VisitAckExecutionResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type AckExecution404JSONResponse Error

func (response AckExecution404JSONResponse) VisitAckExecutionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthRequestObject struct {
	Params GetHealthParams
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListJobsRequestObject struct {
	Params ListJobsParams
}

type ListJobsResponseObject interface {
	VisitListJobsResponse(w http.ResponseWriter) error
}

type ListJobs200JSONResponse struct {
	Jobs []Job `json:"jobs"`
}

func (response ListJobs200JSONResponse) VisitListJobsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateJobRequestObject struct {
	Body *CreateJobJSONRequestBody
}

type CreateJobResponseObject interface {
	VisitCreateJobResponse(w http.ResponseWriter) error
}

type CreateJob201JSONResponse JobDetail

func (response CreateJob201JSONResponse) VisitCreateJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateJob422JSONResponse Error

func (response CreateJob422JSONResponse) VisitCreateJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type DeleteJobRequestObject struct {
	Id JobId `json:"id"`
}

type DeleteJobResponseObject interface {
	VisitDeleteJobResponse(w http.ResponseWriter) error
}

type DeleteJob204Response struct {
}

func (response DeleteJob204Response) VisitDeleteJobResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteJob404JSONResponse Error

func (response DeleteJob404JSONResponse) VisitDeleteJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetJobRequestObject struct {
	Id JobId `json:"id"`
}

type GetJobResponseObject interface {
	VisitGetJobResponse(w http.ResponseWriter) error
}

type GetJob200JSONResponse JobDetail

func (response GetJob200JSONResponse) VisitGetJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetJob404JSONResponse Error

func (response GetJob404JSONResponse) VisitGetJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateJobRequestObject struct {
	Id   JobId `json:"id"`
	Body *UpdateJobJSONRequestBody
}

type UpdateJobResponseObject interface {
	VisitUpdateJobResponse(w http.ResponseWriter) error
}

type UpdateJob200JSONResponse JobDetail

func (response UpdateJob200JSONResponse) VisitUpdateJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateJob404JSONResponse Error

func (response UpdateJob404JSONResponse) VisitUpdateJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateJob422JSONResponse Error

func (response UpdateJob422JSONResponse) VisitUpdateJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type ListExecutionsRequestObject struct {
	Id     JobId `json:"id"`
	Params ListExecutionsParams
}

type ListExecutionsResponseObject interface {
	VisitListExecutionsResponse(w http.ResponseWriter) error
}

type ListExecutions200JSONResponse struct {
	Executions []Execution `json:"executions"`
}

func (response ListExecutions200JSONResponse) VisitListExecutionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetNextRunRequestObject struct {
	Id JobId `json:"id"`
}

type GetNextRunResponseObject interface {
	VisitGetNextRunResponse(w http.ResponseWriter) error
}

type GetNextRun200JSONResponse NextRunResponse

func (response GetNextRun200JSONResponse) VisitGetNextRunResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetNextRun404JSONResponse Error

func (response GetNextRun404JSONResponse) VisitGetNextRunResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PauseJobRequestObject struct {
	Id JobId `json:"id"`
}

type PauseJobResponseObject interface {
	VisitPauseJobResponse(w http.ResponseWriter) error
}

type PauseJob200JSONResponse Job

func (response PauseJob200JSONResponse) VisitPauseJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PauseJob404JSONResponse Error

func (response PauseJob404JSONResponse) VisitPauseJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ResumeJobRequestObject struct {
	Id JobId `json:"id"`
}

type ResumeJobResponseObject interface {
	VisitResumeJobResponse(w http.ResponseWriter) error
}

type ResumeJob200JSONResponse Job

func (response ResumeJob200JSONResponse) VisitResumeJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ResumeJob404JSONResponse Error

func (response ResumeJob404JSONResponse) VisitResumeJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type TriggerJobRequestObject struct {
	Id JobId `json:"id"`
}

type TriggerJobResponseObject interface {
	VisitTriggerJobResponse(w http.ResponseWriter) error
}

type TriggerJob201JSONResponse Execution

func (response TriggerJob201JSONResponse) VisitTriggerJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type TriggerJob404JSONResponse Error

func (response TriggerJob404JSONResponse) VisitTriggerJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type TriggerJob409JSONResponse Error

func (response TriggerJob409JSONResponse) VisitTriggerJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type ResolveScheduleRequestObject struct {
	Body *ResolveScheduleJSONRequestBody
}

type ResolveScheduleResponseObject interface {
	VisitResolveScheduleResponse(w http.ResponseWriter) error
}

type ResolveSchedule200JSONResponse ResolveScheduleResponse

func (response ResolveSchedule200JSONResponse) VisitResolveScheduleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ResolveSchedule422JSONResponse Error

func (response ResolveSchedule422JSONResponse) VisitResolveScheduleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List API keys in caller's namespace
	// (GET /api-keys)
	ListAPIKeys(ctx context.Context, request ListAPIKeysRequestObject) (ListAPIKeysResponseObject, error)
	// Create a new API key
	// (POST /api-keys)
	CreateAPIKey(ctx context.Context, request CreateAPIKeyRequestObject) (CreateAPIKeyResponseObject, error)
	// Revoke an API key
	// (DELETE /api-keys/{id})
	DeleteAPIKey(ctx context.Context, request DeleteAPIKeyRequestObject) (DeleteAPIKeyResponseObject, error)
	// List unacknowledged completed/failed executions
	// (GET /executions/pending-ack)
	ListPendingAck(ctx context.Context, request ListPendingAckRequestObject) (ListPendingAckResponseObject, error)
	// Get execution detail with delivery attempts
	// (GET /executions/{id})
	GetExecution(ctx context.Context, request GetExecutionRequestObject) (GetExecutionResponseObject, error)
	// Acknowledge an execution result
	// (POST /executions/{id}/ack)
	AckExecution(ctx context.Context, request AckExecutionRequestObject) (AckExecutionResponseObject, error)
	// Health check
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// List jobs in caller's namespace
	// (GET /jobs)
	ListJobs(ctx context.Context, request ListJobsRequestObject) (ListJobsResponseObject, error)
	// Create a new cron job
	// (POST /jobs)
	CreateJob(ctx context.Context, request CreateJobRequestObject) (CreateJobResponseObject, error)
	// Delete a job and its data
	// (DELETE /jobs/{id})
	DeleteJob(ctx context.Context, request DeleteJobRequestObject) (DeleteJobResponseObject, error)
	// Get job detail with recent executions
	// (GET /jobs/{id})
	GetJob(ctx context.Context, request GetJobRequestObject) (GetJobResponseObject, error)
	// Partial update a job
	// (PATCH /jobs/{id})
	UpdateJob(ctx context.Context, request UpdateJobRequestObject) (UpdateJobResponseObject, error)
	// List executions for a job
	// (GET /jobs/{id}/executions)
	ListExecutions(ctx context.Context, request ListExecutionsRequestObject) (ListExecutionsResponseObject, error)
	// Get next scheduled run time
	// (GET /jobs/{id}/next-run)
	GetNextRun(ctx context.Context, request GetNextRunRequestObject) (GetNextRunResponseObject, error)
	// Pause a job (set enabled=false)
	// (POST /jobs/{id}/pause)
	PauseJob(ctx context.Context, request PauseJobRequestObject) (PauseJobResponseObject, error)
	// Resume a paused job (set enabled=true)
	// (POST /jobs/{id}/resume)
	ResumeJob(ctx context.Context, request ResumeJobRequestObject) (ResumeJobResponseObject, error)
	// Trigger immediate execution
	// (POST /jobs/{id}/trigger)
	TriggerJob(ctx context.Context, request TriggerJobRequestObject) (TriggerJobResponseObject, error)
	// Resolve natural language to cron expression
	// (POST /schedules/resolve)
	ResolveSchedule(ctx context.Context, request ResolveScheduleRequestObject) (ResolveScheduleResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListAPIKeys operation middleware
func (sh *strictHandler) ListAPIKeys(w http.ResponseWriter, r *http.Request, params ListAPIKeysParams) {
	var request ListAPIKeysRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAPIKeys(ctx, request.(ListAPIKeysRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAPIKeys")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAPIKeysResponseObject); ok {
		if err := validResponse.VisitListAPIKeysResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateAPIKey operation middleware
func (sh *strictHandler) CreateAPIKey(w http.ResponseWriter, r *http.Request) {
	var request CreateAPIKeyRequestObject

	var body CreateAPIKeyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAPIKey(ctx, request.(CreateAPIKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAPIKey")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateAPIKeyResponseObject); ok {
		if err := validResponse.VisitCreateAPIKeyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteAPIKey operation middleware
func (sh *strictHandler) DeleteAPIKey(w http.ResponseWriter, r *http.Request, id APIKeyId) {
	var request DeleteAPIKeyRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteAPIKey(ctx, request.(DeleteAPIKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteAPIKey")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteAPIKeyResponseObject); ok {
		if err := validResponse.VisitDeleteAPIKeyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListPendingAck operation middleware
func (sh *strictHandler) ListPendingAck(w http.ResponseWriter, r *http.Request, params ListPendingAckParams) {
	var request ListPendingAckRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListPendingAck(ctx, request.(ListPendingAckRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPendingAck")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListPendingAckResponseObject); ok {
		if err := validResponse.VisitListPendingAckResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetExecution operation middleware
func (sh *strictHandler) GetExecution(w http.ResponseWriter, r *http.Request, id ExecutionId) {
	var request GetExecutionRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetExecution(ctx, request.(GetExecutionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetExecution")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetExecutionResponseObject); ok {
		if err := validResponse.VisitGetExecutionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AckExecution operation middleware
func (sh *strictHandler) AckExecution(w http.ResponseWriter, r *http.Request, id ExecutionId) {
	var request AckExecutionRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AckExecution(ctx, request.(AckExecutionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AckExecution")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AckExecutionResponseObject); ok {
		if err := validResponse.VisitAckExecutionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request, params GetHealthParams) {
	var request GetHealthRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListJobs operation middleware
func (sh *strictHandler) ListJobs(w http.ResponseWriter, r *http.Request, params ListJobsParams) {
	var request ListJobsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListJobs(ctx, request.(ListJobsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListJobs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListJobsResponseObject); ok {
		if err := validResponse.VisitListJobsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateJob operation middleware
func (sh *strictHandler) CreateJob(w http.ResponseWriter, r *http.Request) {
	var request CreateJobRequestObject

	var body CreateJobJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateJob(ctx, request.(CreateJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateJobResponseObject); ok {
		if err := validResponse.VisitCreateJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteJob operation middleware
func (sh *strictHandler) DeleteJob(w http.ResponseWriter, r *http.Request, id JobId) {
	var request DeleteJobRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteJob(ctx, request.(DeleteJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteJobResponseObject); ok {
		if err := validResponse.VisitDeleteJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetJob operation middleware
func (sh *strictHandler) GetJob(w http.ResponseWriter, r *http.Request, id JobId) {
	var request GetJobRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetJob(ctx, request.(GetJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetJobResponseObject); ok {
		if err := validResponse.VisitGetJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateJob operation middleware
func (sh *strictHandler) UpdateJob(w http.ResponseWriter, r *http.Request, id JobId) {
	var request UpdateJobRequestObject

	request.Id = id

	var body UpdateJobJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateJob(ctx, request.(UpdateJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateJobResponseObject); ok {
		if err := validResponse.VisitUpdateJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListExecutions operation middleware
func (sh *strictHandler) ListExecutions(w http.ResponseWriter, r *http.Request, id JobId, params ListExecutionsParams) {
	var request ListExecutionsRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListExecutions(ctx, request.(ListExecutionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListExecutions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListExecutionsResponseObject); ok {
		if err := validResponse.VisitListExecutionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetNextRun operation middleware
func (sh *strictHandler) GetNextRun(w http.ResponseWriter, r *http.Request, id JobId) {
	var request GetNextRunRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetNextRun(ctx, request.(GetNextRunRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetNextRun")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetNextRunResponseObject); ok {
		if err := validResponse.VisitGetNextRunResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PauseJob operation middleware
func (sh *strictHandler) PauseJob(w http.ResponseWriter, r *http.Request, id JobId) {
	var request PauseJobRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PauseJob(ctx, request.(PauseJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PauseJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PauseJobResponseObject); ok {
		if err := validResponse.VisitPauseJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ResumeJob operation middleware
func (sh *strictHandler) ResumeJob(w http.ResponseWriter, r *http.Request, id JobId) {
	var request ResumeJobRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ResumeJob(ctx, request.(ResumeJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ResumeJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ResumeJobResponseObject); ok {
		if err := validResponse.VisitResumeJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TriggerJob operation middleware
func (sh *strictHandler) TriggerJob(w http.ResponseWriter, r *http.Request, id JobId) {
	var request TriggerJobRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TriggerJob(ctx, request.(TriggerJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TriggerJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TriggerJobResponseObject); ok {
		if err := validResponse.VisitTriggerJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ResolveSchedule operation middleware
func (sh *strictHandler) ResolveSchedule(w http.ResponseWriter, r *http.Request) {
	var request ResolveScheduleRequestObject

	var body ResolveScheduleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ResolveSchedule(ctx, request.(ResolveScheduleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ResolveSchedule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ResolveScheduleResponseObject); ok {
		if err := validResponse.VisitResolveScheduleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xabXPbuBH+Kxi0M83NSJby0ptUM/3gS9KrkzTx5HL9kvN4VuRKggUCDAA6VjP67x0A",
	"fBVBmool2+03WwCxu8/uPrtY8juNZJJKgcJoOvtOU1CQoEHl/js9P3uHm7PY/s0EndEUzIqOqIAE6Yyy",
	"mI6owq8ZUxjTmVEZjqiOVpiAfWIhVQKGzmiWuZ1mk9qntFFMLOl2O6JvbjDKDJPieCLeyvnxDn/PEmbO",
	"LWSlhK8Zqk0lgtsdtH5qjAvIuKGzp9PpiCZww5Iscf9NSxFMGFyicjI+LhYa+4VItyUsJXTotthZd7JY",
	"SBcASqaoDEO3FikEg/GlhaEGSAwGx4Yl2EZlRFHAnKPDPF+bS8kRhF1k8QBkR5TDHHnthPqKNpeZ7tdJ",
	"ZJxbJQqftk6xwOkUIgzI2NZj4osPkmp/oVtl56iO0kUpTM6vMDJW2Cu37GH+hF8z1KaNdLfFe+jaVvN2",
	"fXQqhcbDuP7O3u2zdUSNXKPw0a0jxVLLHHRGzznY2L4xxG04IR8F3xCFJlMCYyIFcbYwKU6CWTzI2172",
	"QF+/lfNOR4MAvjEs0u0lhQaF1fNSYyRF7H4sGeLn6YuXjjKY8D+E+aKlUqSkuMSbVKHWDrAO3MOQw9Jp",
	"8WeFCzqjf5pU5WKSc8jkM/itLMH/SBE+5xvOV1KurWEKTe8We47MTB2Dks2e1ynz5zoYT9tgVEdmig9L",
	"HtqGq2ZY88CQ+98oJVXbsRj+OZJxGK0YDTCua2uViAS1huUAMnCnV/vb6u7s90oGrSrKdCCao7WQ3zjG",
	"yzsy8o/QzcKqfgyCupLzy4FbbRLEGd9TD23AZD40hI3eLxQTZoyrJkxcpkoubfxRGwqcXaNyKwtgtuBc",
	"BA40ii2XqC79QnVsqZ6NBBAZ8MDjIQ7MIdgxsIZ5acSO8Fsp8p8I3Ky6C08MBuagw5lRAddvQ74vJP+t",
	"nB+m2g0h1kM0Q53kfEu1PBB1Z2m8NzR7EW+r5uZMXG+wBnJyI/gaqndEwmvHtI7JOP+4oLMv/YDZ4NmO",
	"2oU7QmEuseBJ9yMzmNzqgIpat66ynfmH/lpqC0rBJlTYL7Yj+gFvzKdM9DVxA2o/3phLlYm9HFw81LR0",
	"2LMNMxMmumzujcvd4l0z4pZ4qVQPxcQn1JJf428563W2cY0WdLcj/QAmU8AJB7HMYImkIFEiFbHKkaZy",
	"rdSt2V32PvT3z69u7V/regwy7y6Rs4PBow+SdljULdgjSCxtWsqIY2YfBX7ewK4fKPoON+Nr4BkSA0uS",
	"AlO2iOINJCl3VsAShQUo4pDFOM4buVRJJ39Gk80Y0pSGmv3fHeP13T/uXLUe+V3hkNeDdsOsMcoUMxub",
	"QIkH9BcEheo0M6s2EZyen5E1boqL6b8g1cRIAqQsdyfF2Mah7I6q0mFlTOrnNSwfzzSPf6WkGIMew1ij",
	"umYRkm/MrMiCKW3GEQetyekZceFErN1qARHqkz/Eh0L8WEcyxXhEkowbNra6QmZWI5JjQ/L+c3Pyh88Q",
	"Y0PUCX7PDJJTd/Y5B2PTmpyen9ERvUblQ4s+PZmeTC3UMkUBKaMz+vxkevLchjOYlcNvAqkT7P5Zeofb",
	"gIViMEjfM238uEK7B6sRZUe1rrZMaiM6W7dv2V0ftm0vLHt4fnS6PZtO/a1NGJef3ymkKWeRU3RypX0y",
	"VTO4Zt4VFg5qC2ozuW2gFaiTmjs3cLlr0U4ei5pwpvNgzpIE1CZHmJQbmCARcI7qL7oKVKtIKnXAPfV5",
	"Uj5QRW1+kfFmL7j68AiN0LZNJOy9ctvy2NMjqZCXzQDM73BD8iaUPHF5Xx9FRfjTDvT+XEsJ+K1wgdtS",
	"5sXkO4u3Pvk5Gmw74LX7vXTAfglSzvgD8f6iTTnWPIXXco2xjYgXfs9BEPbDkwCkH6QhC5mJeAe6T04P",
	"AqKJW9WGT1IUMRPLMUTrXnY59/tOo/VdCSY0n2/cpYe9Wzgs99z1YtJLQLXDh9BQDjWBaN3JRJmoz5WI",
	"Vc9GeDzxExBSE7nr8SJXgq7+FU1l176Orr+surN/BkLfhq9cJH5I+OBJ+Cuayh+5Ur4NKVoHAsZgkpqw",
	"syZ5boZry2m0PprHAux2Wgu7B0e2pozluApkhdreCB2aKzdN64t4P29rgxdiqmtUc6mxQVW7N4Cjxv7O",
	"cDCAlt+xaXTjdPbloo6c30OiFUZrD9OVnPf3l2/thntsLke7ofcPxg0qMt+4W+GTNW5m/pLoS8WIKEwR",
	"jL2Yjcjph9dEYwLCsEj/5G6PKXdvE/x4PeRbA8uGX8sy0L7I7dywtdm4rt9q0lnkqmldT+i0rP4tm3u5",
	"JAETrYgU5ErOST4BDMnJl1pCjlQ6i8AZVDT9dLC/XLoDhxRKG5GdFdKe8mN9utXxmE16bfZwzx16Nc4N",
	"o1m05Y7Ynz07PrH/GziL3YkE8z2dnb+bCl7Z+CnoamDb7/25H2/5j2KGlUQv5eGrodeDgOMHEDFhRpMY",
	"DFjNumrfQcGZ3l+kPqLe7qpUx3d1/l1HowV3w5xo1fZAOY28kxMOz1StKekgpron/3vlYk8G9x8Aj4Mb",
	"z0EZBpz4N3g+63eocdK81XZ2dm+qbT8YhaMjN4KhNqd8uV7hfJBPBbrk7bzDb0sd+CVBhzVMRBgegPS8",
	"Beo6LROG8f1P+/+dqVQh3tkwVifaC0U4oQTemLHKRN9tMn/l/Bir6u7b8BDP4Y0hKhOE5aP1By+vFvPy",
	"9XDsdHPhu+OaFLL8LW2wtT+3y4+32elqc5xVD99aOvTyzvKJRkPyu+zfF8B1PrCv+UKhzpIeZ3xy6/97",
	"3vB2PYaxvtWDQB4ebbfY9qzllbyAdbvls99wUL88ve+hb/0Ke/+N4fRvx5doI5FpEjPt50nN2MidSFiS",
	"YMxsa4g14EZ0UlCptmkq+XV/nta/hTnSVKTjg6J7vnF0ffcTcEC+NS6r0r3dCV7JjMdESENSUBrbtGD1",
	"ImL34yojW99UbXemw82vNL5c2FTWqK6L/HdfgLjPLWaTCZcR8JXUZvZy+nJKtxfb/wYAAP//Gw7woSY1",
	"AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
